### ISSUE TITLE
Error: Asset '725.zip' could not be opened

### ISSUE THREAD

**Issue by TanTouJunJun** [mockingbot/react-native-zip-archive#107]
react-native-cli: 2.0.1
react-native: 0.52.0
"react": "16.2.0",
"react-native-fs": "^2.9.12",
"react-native-zip-archive": "^3.0.1"

安卓环境真机运行报错！
文件所在路径为“/data/user/0/com.fsdemo/files/725.zip”，用 RNFS.exists 确认文件确实存在，但是无法解压成功！
![image](https://user-images.githubusercontent.com/28912294/47000446-e12ec280-d15a-11e8-864a-488c66dfe63a.png)

![image](https://user-images.githubusercontent.com/28912294/47001355-d2e1a600-d15c-11e8-9c97-fdf8994af1ec.png)

**Comment by plrthink** [comment]
抱歉现在才有时间看这个 issue

但根据报错信息，这个问题不在 react-native-zip-archive，是 react-native-fs 的 copyFileAssets 报的错（https://github.com/itinance/react-native-fs/blob/06d609f000eacc69aff69b0a2f9bf17b8811ce9a/android/src/main/java/com/rnfs/RNFSManager.java#L437），而根据代码来看，到这里 rnza 还没有运行，所以你可以继续看看 rnfs 的 doc 找到问题。
