### ISSUE TITLE
zip feature behave differently on ios and android

### ISSUE THREAD

**Issue by jzhw0130** [mockingbot/react-native-zip-archive#108]
Hi, everyone

My scenario is : RN APP zip some files, upload the zip file to BE. BE server will decompress the zip file and do future analy.

The whole process works well if upload zip file from iOS.
The BE server can not decompress the zip file which uploaded from Android.

The BE server(Node) throws a error : 
Error: absolute path: /fileName

Try to debug, find the problem as follows, file name format is different:

ios:
<img width="888" alt="screen shot 2018-10-20 at 4 25 54 pm" src="https://user-images.githubusercontent.com/12521790/47253691-3c2d2600-d489-11e8-9841-6b7466921445.png">

android:
<img width="879" alt="screen shot 2018-10-20 at 4 03 34 pm" src="https://user-images.githubusercontent.com/12521790/47253694-45b68e00-d489-11e8-9985-fff6c07035b3.png">

There is a prefix "/" before the file name.

Error exists : 

<img width="1307" alt="screen shot 2018-10-20 at 5 07 35 pm" src="https://user-images.githubusercontent.com/12521790/47253792-ece7f500-d48a-11e8-867e-3e34282bff86.png">

Could you give me any suggestion?
Thanks a lot

Jing

**Comment by maayannoyhalevi** [comment]
Same here

**Comment by maayannoyhalevi** [comment]
Look at: https://github.com/mockingbot/react-native-zip-archive/pull/113

**Comment by plrthink** [comment]
Yep, it seems like the code on the master branch has solved this problem, could you try that to validate?
