### ISSUE TITLE
No changelog available?

### ISSUE THREAD

**Issue by CauseOfDev** [mockingbot/react-native-zip-archive#114]
Hi,

Is there somewhere a changelog we can view? More specifically, what are the (breaking) changes coming from v2.2.6 / going to v3.0.0? 

Thank you in advance.

**Comment by ThatBean** [comment]
Currently you can check:
> https://github.com/mockingbot/react-native-zip-archive/releases

and for v3.0.0:
> https://github.com/mockingbot/react-native-zip-archive/releases/tag/v3.0.0
> 
> Breaking changes:
> - compatible with React Native 0.56, need to update your app's targetSdkVersion to at least 26.
