### ISSUE TITLE
React native adding password protection while creating zip

### ISSUE THREAD

**Issue by premmkumar09** [mockingbot/react-native-zip-archive#123]
Is there any way to create a password protected zip file using this plugin. I see option for creating a zip file which works perfectly, but i am not able to find any way to add password protection to the zip file.

**Comment by Freir96** [comment]
When can it be expected to be ready? I do not rush anyone, but I just would like to know if there is point of trying to implement a native solution in my project.

**Comment by plrthink** [comment]
Thanks for the nice work of @brystfire08, it has been implemented on the Android in this PR https://github.com/mockingbot/react-native-zip-archive/pull/133, but still not available on iOS. So I would be going to try this in this weekend and hopefully it would be released on the next week. You can track this progress in this opening PR.

**Comment by lapsio** [comment]
Is it merged already? I need this feature ASAP otherwise I'll need to encrypt zip with plain AES256 :C

**Comment by plrthink** [comment]
Sorry, the iOS part is not ready yet, which I'm planning to work on these days. If you're just dealing it on Android, you can use the code in that PR.

**Comment by ramya123coder** [comment]
When will the next version be released? Just wanted to know as I have already used the code in PR#133  but thought it would be cleaner if I can update the library version.

**Comment by plrthink** [comment]
@ramya123coder All the relative code has been merged into master and intended to be shipped today.

**Comment by plrthink** [comment]
Thanks to the work in https://github.com/mockingbot/react-native-zip-archive/pull/133. This functionality is supported in the latest release. Details in https://github.com/mockingbot/react-native-zip-archive/releases/tag/4.1.0.
