### ISSUE TITLE
react native项目配置有私库，但是我在xcode项目运行的时候，错误如下。

### ISSUE THREAD

**Issue by pjxFreeMan** [mockingbot/react-native-zip-archive#124]
错误如下：
no such file or directory: '/Users/pangjiaxing/Library/Developer/Xcode/DerivedData/PHMobile-dfjvqacibwotrdbmdazqgojgvbhl/Build/Products/Release-iphoneos/libRNZipArchive.a

 "react-native-zip-archive": "2.1.0"

"repository": {
    "type": "git",
    "url": "git@github.com:plrthink/react-native-zip-archive.git"
  },

自己的解决思路是：
找到libRNZipArchive.a放置到对应的目录下，但是我并不能找到这个文件在github上

**Comment by plrthink** [comment]
这个文件就是 react-native-zip-archive 本身，你可以尝试 `react-native link react-native-zip-archive`，或是按照文档里描述的 manually linking 来 link 这个库。
