### ISSUE TITLE
Support for multi-part zip files

### ISSUE THREAD

**Issue by ghost** [mockingbot/react-native-zip-archive#125]
Hello, good package, I like it. I wanna ask: is this package supports multi-part zip files? Can I use this package to unzip multi-part zip file into one?

**Comment by NelGarbuzova** [comment]
It seems, that `react-native-zip-archive` does not support multi-part zip files. Gives the error:
`Error: Failed to extract file Not a zip archive`

**Comment by plrthink** [comment]
Yes, it's a not implemented feature. Perhaps we can make it, PRs are open.
