### ISSUE TITLE
unzip on ios fails with the below error

### ISSUE THREAD

**Issue by manujbahl** [mockingbot/react-native-zip-archive#126]
{
    "framesToPop": 1,
    "code": "unzip_error",
    "nativeStackIOS": [
        "0   StepFour                            0x0000000104d1d3f7 RCTJSErrorFromCodeMessageAndNSError + 135",
        "1   StepFour                            0x0000000104cb1303 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.129 + 179",
        "2   StepFour                            0x0000000104c09521 -[RNZipArchive unzip:destinationPath:resolver:rejecter:] + 369",
        "3   CoreFoundation                      0x000000010c53f4cc __invoking___ + 140",
        "4   CoreFoundation                      0x000000010c53ca45 -[NSInvocation invoke] + 325",
        "5   CoreFoundation                      0x000000010c53ce96 -[NSInvocation invokeWithTarget:] + 54",
        "6   StepFour                            0x0000000104cb30ca -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2810",
        "7   StepFour                            0x0000000104d651c6 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 790",
        "8   StepFour                            0x0000000104d64cd3 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 131",
        "9   StepFour                            0x0000000104d64c49 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 25",
        "10  libdispatch.dylib                   0x000000010e836ccf _dispatch_call_block_and_release + 12",
        "11  libdispatch.dylib                   0x000000010e837d02 _dispatch_client_callout + 8",
        "12  libdispatch.dylib                   0x000000010e83e720 _dispatch_lane_serial_drain + 705",
        "13  libdispatch.dylib                   0x000000010e83f261 _dispatch_lane_invoke + 398",
        "14  libdispatch.dylib                   0x000000010e847fcb _dispatch_workloop_worker_thread + 645",
        "15  libsystem_pthread.dylib             0x000000010ec19611 _pthread_wqthread + 421",
        "16  libsystem_pthread.dylib             0x000000010ec193fd start_wqthread + 13"
    ],
    "domain": "RCTErrorDomain",
    "userInfo": null
}

**Comment by manujbahl** [comment]
The erro coming back from the bridge is this .. 
{code: "unzip_error", message: "unable to unzip", nativeStackIOS: Array(17), domain: "RCTErrorDomain", userInfo: null}
code: "unzip_error"
domain: "RCTErrorDomain"
message: "unable to unzip"
nativeStackIOS: Array(17)
0: "0   StepFour                            0x0000000107d4de07 RCTJSErrorFromCodeMessageAndNSError + 135"
1: "1   StepFour                            0x0000000107ce1d13 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.129 + 179"
2: "2   StepFour                            0x0000000107c39f31 -[RNZipArchive unzip:destinationPath:resolver:rejecter:] + 369"
3: "3   CoreFoundation                      0x000000010f6504cc __invoking___ + 140"
4: "4   CoreFoundation                      0x000000010f64da45 -[NSInvocation invoke] + 325"
5: "5   CoreFoundation                      0x000000010f64de96 -[NSInvocation invokeWithTarget:] + 54"
6: "6   StepFour                            0x0000000107ce3ada -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2810"
7: "7   StepFour                            0x0000000107d95bd6 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 790"
8: "8   StepFour                            0x0000000107d956e3 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 131"
9: "9   StepFour                            0x0000000107d95659 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 25"
10: "10  libdispatch.dylib                   0x0000000111942ccf _dispatch_call_block_and_release + 12"
11: "11  libdispatch.dylib                   0x0000000111943d02 _dispatch_client_callout + 8"
12: "12  libdispatch.dylib                   0x000000011194a720 _dispatch_lane_serial_drain + 705"
13: "13  libdispatch.dylib                   0x000000011194b261 _dispatch_lane_invoke + 398"
14: "14  libdispatch.dylib                   0x0000000111953fcb _dispatch_workloop_worker_thread + 645"
15: "15  libsystem_pthread.dylib             0x0000000111d25611 _pthread_wqthread + 421"
16: "16  libsystem_pthread.dylib             0x0000000111d253fd start_wqthread + 13"
length: 17
__proto__: Array(0)
userInfo: null
__proto__: Object

**Comment by hariDasu** [comment]
why did you close this error @manujbahl
