### ISSUE TITLE
Build fails with Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by kaaoo** [mockingbot/react-native-zip-archive#132]
Here is error that I got:
`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RNZASSZipArchive", referenced from:
      objc-class-ref in libRNZipArchive.a(RNZipArchive.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Can anybody explain what does it mean? and how to handle this?
Many thanks)

**Comment by kaaoo** [comment]
Well, seems like there was some issue with RN cache, cleaning it helped (ios/build folder). Closing issue.

**Comment by sidhiartha** [comment]
Hi @kaaoo , 
I just got this error right now.
can you explain which build folder we need to clean?

I try to clean build folder from XCode, either with `option` or not,
but the error won't disappear.

I look on `rootProject/ios` but there are no build folder in it.

Thank you in advance

**Comment by kaaoo** [comment]
Hi @sidhiartha, In my case I just removed ios/build folder and ios/Pods folder (don't forget to run pod install after that). Also, I would suggest to remove node_modules and rebuild again.

**Comment by sidhijakpat** [comment]
Hi @kaaoo ,
it have been working after restarting my computer, after deleting `ios/build`.

Maybe on my case, there are some cache from XCode 

Thank you for your information.
