### ISSUE TITLE
[Android] Fixing a Zip Path Traversal Vulnerability

### ISSUE THREAD

**Issue by nick-creston** [mockingbot/react-native-zip-archive#134]
Hey. I received a message in the Google Play console:
![alert](https://user-images.githubusercontent.com/8370648/58228479-afb15180-7d50-11e9-9930-cbdf07061eb4.png)

How to fix: https://support.google.com/faqs/answer/9294009

I'm not sure, but a possible fix is here:
https://github.com/mockingbot/react-native-zip-archive/blob/master/android/src/main/java/com/rnziparchive/RNZipArchiveModule.java#L245-L251

**Comment by kevinkevw** [comment]
I received the same security alert as well.

**Comment by sbayd** [comment]
+ 1, Same security Alert. 

<img width="500" alt="Screen Shot 2019-05-24 at 09 07 10" src="https://user-images.githubusercontent.com/6469914/58306188-6968fa80-7e03-11e9-8387-c3abe137996a.png">

**Comment by punjasin** [comment]
same as well

**Comment by plrthink** [comment]
Thanks for reporting, would solve this ASAP

**Comment by sbayd** [comment]
@plrthink Thank you for all your efforts and attention.

**Comment by plrthink** [comment]
Could you please try the code on the master to see if it would solve the problem? thanks to the PR opened by @ratson, we seems to fix this but still need to verify it.

**Comment by punjasin** [comment]
> Could you please try the code on the master to see if it would solve the problem? thanks to the PR opened by @ratson, we seems to fix this but still need to verify it.



@plrthink i try change the my lib according to ur commit and launch to internal test still have this issue warning

**Comment by plrthink** [comment]
Double check this issue and yeah we still have the problem. I would fix this before this weekend.

**Comment by plrthink** [comment]
Has published a beta version to fix this, please reinstall this using `yarn add react-native-zip-archive@beta` to test it. If the problem is solved then I would publish it as the latest version.

**Comment by 008v** [comment]
same security alert 
![1d6211478ca34774df385eb867506aee](https://user-images.githubusercontent.com/14173882/58926714-aecfe500-877e-11e9-9941-a75b26cf6348.jpg)

**Comment by plrthink** [comment]
@008v Did you say the same result with the beta version of this package?

**Comment by punjasin** [comment]
@plrthink tested it fix the problem :) 
![image](https://user-images.githubusercontent.com/9058090/59011984-77396980-8860-11e9-95e0-34dad7c3184c.png)

**Comment by plrthink** [comment]
@punjasin cool!!! would release it after a few tweaks.

**Comment by neemssoni** [comment]
After upgrading to Version 4.0.3 and submitting the apk to Google Play Console, still I am getting the warning. You can see the release date is June 29, 2019. [
<img width="768" alt="Screenshot 2019-07-01 at 3 21 24 PM" src="https://user-images.githubusercontent.com/18548951/60427279-f6c61880-9c13-11e9-95a1-7a2f65cd7318.png">
](url)

**Comment by plrthink** [comment]
That's wired, could you please double check in the code in your node_modules whether the version is 4.0.3? If the problem still happens, I would dig into this.

**Comment by neemssoni** [comment]
Yes please check. This is my package.json depedencies snippet :`"dependencies": {
    "@babel/core": "7.1.6",
    "@react-navigation/core": "3.2.0",
    "babel-plugin-transform-remove-console": "6.9.4",
    "concurrently": "4.0.1",
    "lodash": "4.17.11",
    "moment": "2.22.2",
    "native-base": "2.12.1",
    "react": "16.6.1",
    "react-native": "0.57.5",
    "react-native-cached-image": "git://github.com/fungilation/react-native-cached-image.git",
    "react-native-charts-wrapper": "0.5.2",
    "react-native-config": "0.11.7",
    "react-native-device-info": "^2.1.2",
    "react-native-email": "1.0.1",
    "react-native-firebase": "5.1.0",
    "react-native-keyboard-aware-scroll-view": "0.6.0",
    "react-native-modal-filter-picker": "1.3.4",
    "react-native-otp-inputs": "1.0.0",
    "react-native-pages": "0.7.0",
    "react-native-pdf": "^5.1.0",
    "react-native-segmented-control-tab": "3.3.1",
    "react-native-sentry": "0.40.3",
    "react-native-splash-screen": "3.1.1",
    "react-native-sqlite-storage": "3.3.8",
    "react-native-zip-archive": "^4.0.3",
    "react-navigation": "2.11.2",
    "react-redux": "5.0.7",
    "redux": "4.0.0",
    "redux-logger": "3.0.1",
    "redux-thunk": "2.2.0",
    "rn-fetch-blob": "0.10.13"
  },`

**Comment by plrthink** [comment]
@neemssoni I guess that it may be relative to the new feature. I would fix this very soon. But please move on to the issue https://github.com/mockingbot/react-native-zip-archive/issues/145 for the further updates.
