### ISSUE TITLE
React native 0.59

### ISSUE THREAD

**Issue by mts88** [mockingbot/react-native-zip-archive#135]
Hi, this is not a bug report. React native 0.59 use react "react": "16.8.6", and in your version 4.0.0 (for RN >=0.58) you limit in package.json version of react.
Can you upgrade? This upper bound create some problem in compiling. Thanks.

**Comment by plrthink** [comment]
Sure, we should update it, will do it ASAP.

**Comment by plrthink** [comment]
The updates have been pushed on the master branch, and it would be released in the next week.

**Comment by plrthink** [comment]
Has been updated with 4.0.3 published.
