### ISSUE TITLE
is it possible to append file to a archive or archive miltiple files?

### ISSUE THREAD

**Issue by AwanesowArtem** [mockingbot/react-native-zip-archive#137]

**Comment by plrthink** [comment]
No, we have implemented this yet, but it seems could be supported technically. Also, PRs are welcome.

**Comment by AwanesowArtem** [comment]
> No, we have implemented this yet, but it seems could be supported technically. Also, PRs are welcome.

But in java code I saw it's possible to archive multiple files or whole folder, this already implemented, correct?

**Comment by plrthink** [comment]
Yes, we can let users zip a single file or a folder.
