### ISSUE TITLE
Could not build module 'Darwin'

### ISSUE THREAD

**Issue by unigeniee** [mockingbot/react-native-zip-archive#142]
I'm getting this issue

`Could not build module 'Darwin'`

Please help me to fix this.
Also, what is `libz` and how to add it to xcode?
Thank you

**Comment by plrthink** [comment]
Sorry for the late response. Have you already figured this out?

For the first question. Actually, I don't know what happened and I can't reproduce this. So an example which can trigger the problem would be helpful.

And you can follow this tutorial http://docs.onemobilesdk.aol.com/ios-ad-sdk/adding-frameworks-xcode.html  to add the `libz` to your target.

**Comment by plrthink** [comment]
Closed due to being not active for a while, but feel free to reopen it if the issue is still bothering you.
