### ISSUE TITLE
Path Traversal vulnerability. 

### ISSUE THREAD

**Issue by ganmor** [mockingbot/react-native-zip-archive#145]
We recently recieved the following warning on google play

Security alert
Your app contains an unsafe unzipping pattern that may lead to a Path Traversal vulnerability. Please see this Google Help Center article to learn how to fix the issue.
Vulnerable locations:
com.rnziparchive.RNZipArchiveModule$2.run

https://support.google.com/faqs/answer/9294009

**Comment by plrthink** [comment]
I think version 4.1.0 has already solved this issue, so please try update to it first. Details in https://github.com/mockingbot/react-native-zip-archive/issues/134.

**Comment by plrthink** [comment]
Oops, it may be caused by the features added after the original fix. Will try to fix it ASAP.

**Comment by plrthink** [comment]
Could you try to use the 4.1.2-beta.0 to verify it? You can install that with `yarn add react-native-zip-archive@4.1.2-beta.0`

**Comment by plrthink** [comment]
This issue should be solved with the release of 4.1.2. So I'm going to close this.

**Comment by learnyst** [comment]
@plrthink this issue is not yet resolved. After updating the lib to 4.1.2 we are still getting the issue

**Comment by LuisRodriguezLD** [comment]
I am seeing this issue on version 5.0

**Comment by plrthink** [comment]
@LuisRodriguezLD Yes, and it still not being fixed. Move to this issue for further updates https://github.com/mockingbot/react-native-zip-archive/issues/170.
