### ISSUE TITLE
Unable to open zipped file with password in ios.

### ISSUE THREAD

**Issue by ramya123coder** [mockingbot/react-native-zip-archive#148]
When trying to zipWithPassword files on the  app using this package, I cannot open the resulting zipped file with password . zipWithPassword is working fine in android , the problem exists only when files are zippedWithPassword in IOS device.

[react_zip_withPassword.zip](https://github.com/mockingbot/react-native-zip-archive/files/3345570/react_zip_withPassword.zip)

Unable to expand "react_zip_withPassword.zip" into "Desktop". (Error 1 - Operation not permitted.)

**Comment by plrthink** [comment]
TLDR; You should use the third party compress app like The Unarchiver to unzip it on the mac. The native one would not work.

We're using the [AES](https://en.wikipedia.org/wiki/Advanced_Encryption_Standard) on the iOS platform to do the zip which cannot be changed at this time. But the native compress tool on the MacOS doesn't support it yet.

This behavior is inherited from the [SSZipArchive](https://github.com/ZipArchive/ZipArchive) which we're using under the hood. And you can see more info on this [issue](https://github.com/ZipArchive/ZipArchive/issues/518).

**Comment by ramya123coder** [comment]
oh..okay.Thank you.
