### ISSUE TITLE
Support for ZipFile constructor with Charset

### ISSUE THREAD

**Issue by seightday** [mockingbot/react-native-zip-archive#149]
When I unzip a zip file which contains chinese charater ZipEntry will fail with Failed to extract file MALFORMED[1].
I have to modify the source code, change  ZipFile zipFile = new ZipFile(zipFilePath) to  ZipFile zipFile = new ZipFile(zipFilePath,Charset.forName("GBK")), then it works.

**Comment by plrthink** [comment]
Cool, thanks for reporting the issue. It would be wonderful if you open a PR to address this.

**Comment by ImHeXin** [comment]
I opened a PR about charset @plrthink @seightday 
Welcome to give some advice！

**Comment by bimbox-open** [comment]
Hi, can you update project to next version 4.1.3 @plrthink

**Comment by plrthink** [comment]
@bimbox-open just shipped 4.1.3 with this fix.
