### ISSUE TITLE
Cannot unzip on IOS

### ISSUE THREAD

**Issue by Corydeeee** [mockingbot/react-native-zip-archive#152]
I am react 59.3 and am unable to get any IOS files to unzip. I am using react-native-document-picker to retrieve the file location and successfully copy it to DocumentDirectoryPath with RNFS. From there I am copying your exact example for unzip and everytime I get a unzip error.

**Comment by plrthink** [comment]
Could you upload the file you want to unzip? I can test it locally to see what exactly happened?

**Comment by plrthink** [comment]
You can now install the version 4.1.4 which improves the error message on iOS and you can see the details about the error. That would be helpful to fix the problem.

**Comment by darth-veitcher** [comment]
Having a similar(?) issue using a known good .zip file. Only getting `Error: failed to open zip file` from the library. Is there any way to turn on more verbose output?

**Comment by plrthink** [comment]
@darth-veitcher can you update the package to the 4.1.4 or higher? You would receive a more verbose error message for debugging.

**Comment by darth-veitcher** [comment]
I'm running `^5.0.0` by the looks of things in my package.json. The output I get is as follows:

```
[Unhandled promise rejection: Error: failed to open zip file]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:155:41 in createErrorFromErrorData
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:55 in <unknown>
- ... 5 more stack frames from framework internals
```

**Comment by darth-veitcher** [comment]
To clarify, I'm attempting to download a file and then extract it. Example code below.

```
import {FileSystem} from 'react-native-unimodules';
import {unzip} from 'react-native-zip-archive';

.. ..

<Button 
        title="Download sample"
        onPress={() => {
          console.log("downloading sample")
          const localDir = FileSystem.documentDirectory
          const callback = downloadProgress => {
            const progress = (downloadProgress.totalBytesWritten / downloadProgress.totalBytesExpectedToWrite) * 100;
            console.log("Progress: "+progress);
          };
          FileSystem.makeDirectoryAsync(localDir, {intermediates: true})
          .then(res = async() => {
            const dl = await FileSystem.createDownloadResumable('https://file-examples.com/wp-content/uploads/2017/02/zip_2MB.zip', localDir+'zip_2MB.zip', {}, callback)
            .downloadAsync().then(uri => {
              console.log("Finished downloading to ", uri);
              console.log("Extracting to "+localDir);
              unzip(uri.uri, localDir);
            })
          })
        }}
      />
```

**Comment by darth-veitcher** [comment]
Doing a little more digging this might be to do with file permissions perhaps of the downloads created by Expo? Tweaking the code to use `react-native-fetch-blob` as opposed to the Expo FileSystem approach results in a successful unzip of the test file.

**Comment by plrthink** [comment]
@darth-veitcher sorry for the late response, and yes that seems like the problem the creation of the file, not with unzipping progress.

**Comment by darth-veitcher** [comment]
No worries. Might be good to somehow test/catch for this and raise an error though as the provided exception message wasn’t very descriptive?

**Comment by plrthink** [comment]
@darth-veitcher Actually we're bypassing the error message from the underlying package(SSZipArchive on iOS), so maybe there's a way to get a more verbose version of the errors. 

Will search for that. Also, PRs are welcome!

**Comment by plrthink** [comment]
Closed due to being not active for a while, but feel free to reopen it if the issue is still bothering you.

**Comment by ericluong** [comment]
@darth-veitcher  I was facing the same issue when trying to unzip a file that was downloaded with Expo [FileSystem API](https://docs.expo.io/versions/latest/sdk/filesystem/) in a bare workflow.

This was caused by the API convention :
> The API takes file:// URIs pointing to local files on the device to identify files

For example, Expo documentDirectory is something like `file:///path/to/my/document/` whereas RNFS documentDirectory is `/path/to/my/document`.

I solved it by trimming the `file:///` prefix from the source and target destination.

For example:

```javascript
const DIRECTORY = FileSystem.documentDirectory;
const UNPREFIXED_SCORM_DIRECTORY = `/${DIRECTORY.replace(/^file:\/\/\//g, '')}`;
```

Haven't tested it on Android though.
