### ISSUE TITLE
Unable to zip (iOS)

### ISSUE THREAD

**Issue by sentry0** [mockingbot/react-native-zip-archive#156]
react-native 0.60.4
react-native-zip-archive 4.1.1

Works great on Android but I keep seeing the message "unable to zip" on iOS.  

Anyone else having this issue?

`async backup() {
        let result = {
            backupSuccess: false,
            backupName: null,
            error: null
        };

        try {
            const now = moment().format('YYYYMMDDhhmmss');
            const backupName = `OpenD6Toolkit_${now}.zip`;
            const appDir = await this._getPath(DEFAULT_ROOT_DIR);
            const archiveDir = Platform.os === 'ios' ? RNFetchBlob.fs.dirs.DocumentDir : RNFetchBlob.fs.dirs.DownloadDir;
            const characterDir = await this._getPath(DEFAULT_CHARACTER_DIR);
            const templateDir = await this._getPath(DEFAULT_TEMPLATE_DIR);
            const backupDir = appDir + '/backup_' + now;

            await this._makeBackupDir(backupDir);
            await this._copyCharactersAndTemplates(backupDir, characterDir, templateDir);
            Alert.alert(backupDir);
            await zip(backupDir, archiveDir + '/' + backupName);
            await RNFetchBlob.fs.unlink(backupDir);

            result.backupSuccess = true;
            result.backupName = backupName;
        } catch (error) {
            result.error = error.message;
        }

        return result;
    }`

**Comment by sentry0** [comment]
Error on my part...lib works great :P

**Comment by plrthink** [comment]
Also, you should use version 5.0.0-alpha.0 of this package to adopt for react-native 60.
