### ISSUE TITLE
iOS, no progress calls

### ISSUE THREAD

**Issue by BeauCarrel** [mockingbot/react-native-zip-archive#162]
Hello, first off thanks for this great package, It has helped me lots.

I just have a small problem, I can see that it has been an issue before and has been resolved by updates, but it seems broken again in the latest version.

I am developing an application for iOS only, which involves de-zipping a 7GB file. That works perfectly but I cannot get the progress callback to work, the callback is invoked at the started with a progress of 0, and once at the end with a progress of 1.

react-native-zip-archive version: 4.1.2 (I also tried with 4.1.1)
react-native: 0.59.9
iOS: 12.4

Here is my javascript:

```
let unzipping = unzip(RNFetchBlob.fs.dirs.DocumentDir + `/cadastre-${cadastreVersion}.zip`, RNFetchBlob.fs.dirs.DocumentDir + `/cadastre-${cadastreVersion}`)

let zipProgress = subscribe(({ progress }) => {
    console.log('UNZIPPING', progress)
    progresses[2] = progress
    dispatch({
        type: UPDATE_PROGRESS,
        payload: getTotalProgress(progresses)
    })
})

await unzipping

zipProgress.remove()
```

I've also tried it like this:

```
let zipProgress = subscribe(({ progress }) => {
    console.log('UNZIPPING', progress)
    progresses[2] = progress
    dispatch({
        type: UPDATE_PROGRESS,
        payload: getTotalProgress(progresses)
    })
})

await unzip(RNFetchBlob.fs.dirs.DocumentDir + `/cadastre-${cadastreVersion}.zip`, RNFetchBlob.fs.dirs.DocumentDir + `/cadastre-${cadastreVersion}`)

zipProgress.remove()
```

Thanks in advance for any help
Regards,
Beau

**Comment by plrthink** [comment]
Hi, @BeauCarrel 

Thanks for reporting, I confirmed this issue is caused by updating the underlying library 'SSZipArchive' which introduces the changes the way how progress emitter works. I would plan to fix this in weeks.

**Comment by BeauCarrel** [comment]
Hi @plrthink 
Thank you for the reply, good to hear you've found the source of the problem!
I looked at the commit history, and I've rolled back to version 4.0.3 before the update of 'SSZipArchive' and I can confirm that the progress update works.

**Comment by plrthink** [comment]
Hi, @BeauCarrel 

I just opened the PR to address this issue at https://github.com/mockingbot/react-native-zip-archive/pull/167. Could you please test it with the version `4.1.5-beta.0` on the npm? Would do the release if it works on your usecase.

**Comment by plrthink** [comment]
Closed with 4.1.5 shipped to npm, but feel free to reopen it if still have issues.

**Comment by jeffmon** [comment]
@plrthink 

I updated `react-native-zip-archive` from `4.1.1`to `4.1.5`to hopefully get the progress working and now I'm getting this error:

![Screen Shot 2019-10-24 at 8 52 48 PM](https://user-images.githubusercontent.com/18548300/67549595-5901c800-f6a0-11e9-99f6-b3e01588c127.png)
 
I'm using the exact same code from `4.1.1`:

      unzip(`${DATABASE_DIR}/database.zip`, DATABASE_DIR).then(() =>
        RNFetchBlob.fs.unlink(`${DATABASE_DIR}/database.zip`).then(async () => {
          let gudid_db = await SQLite.openDatabase(
            {
              name: 'gudid.db',
              readonly: true,
              createFromLocation: 'guidid.sqlite3.db'
            },
            () => store.dispatch(enableDb(gudid_db))
          );
        })
      );

**Comment by jeffmon** [comment]
@plrthink Sorry for the late response, but yes, I clear the cache, clear `node_modules` and it all leads to that same error.

**Comment by plrthink** [comment]
@jeffmon That's wired, just test that on our example app but don't face the problem. Could you please attach a project that can reproduce this issue?  That would be much helpful to see what's happening.
