### ISSUE TITLE
RNZipArchive.unzip got 5 arguments, expected 4

### ISSUE THREAD

**Issue by ahmadqwer** [mockingbot/react-native-zip-archive#166]
Hello,
After updating my react-native version from 0.57.8 to 0.59.10 to be able to get 64-bit APK, the library worked but i had to update it from `react-native-zip-archive@3.0.1` to `react-native-zip-archive@4.1.4` to Fix zip traversal vulnerability.
but now when in try to unzip i got the below error on Android.
`RNZipArchive.unzip got 5 arguments, expected 4`

below is the unzipping code
```
unzip(RNFS.DocumentDirectoryPath+'/'+bookId+'.zip', bookPath)
 // some code
})
```

can you help me with this?
Thank you.

**Comment by plrthink** [comment]
That's wired since I have double-checked the signature of the method and they indeed match each other.

Did you try to clean up all the things like stop builds and start again? Maybe related to the cache.

**Comment by plrthink** [comment]
Closed due to being not active for a while, but feel free to reopen it if the issue is still bothering you.
