### ISSUE TITLE
duplicate symbol _OBJC_IVAR_$_SSZipArchive._zip

### ISSUE THREAD

**Issue by plrthink** [mockingbot/react-native-zip-archive#17]
If you're using other react native package which also includes in SSZipArchive like [react-native-code-push](https://github.com/Microsoft/react-native-code-push), you may face this issue when trying to build your app.

The problem is straightforward. Since we're both want to link some file in SSZipArchive so the linker would fail.

I'm trying to solve this issue. Any guide would be thankful.

**Comment by itinance** [comment]
From the [codepush-docs](https://microsoft.github.io/code-push/docs/react-native.html#link-3):

> 
> CodePush depends on an internal copy of the SSZipArchive library, so if your project already includes it (either directly or via a transitive dependency), then you can install a version of CodePush which excludes it by depending specifically on the Core subspec:
> 
> pod 'CodePush', :path => './node_modules/react-native-code-push', :subspecs => ['Core']
> NOTE: The above paths needs to be relative to your app’s Podfile, so adjust it as nec cessary.

Have you tried this out?

**Comment by plrthink** [comment]
@itinance Thanks for your advice, haven't tried it yet but it seems like a solution. But still think there would be a better one.

For temporarily fixing this problem you can try install this module via github with custom-ssziparchive branch by place this in your package.json
```json
"react-native-zip-archive": "plrthink/react-native-zip-archive#custom-ssziparchive"
```

**Comment by itinance** [comment]
Good catch!

**Comment by itinance** [comment]
I'd like to help if you would provide more info how to reproduce this linker error. Would it be enough just to install code-push and this library together?

**Comment by plrthink** [comment]
Yeah, and link both packages.

**Comment by chirag04** [comment]
@itinance @plrthink if you install code push from cocopod you need react-native to be installed from cocopod as well. this does not play well with other rn modules.

I have a fork that removes the ssarchive directory and defines a header search path that links ssarchive from code-push directory. I know this does not work for everyone. wish there was a middle ground.

**Comment by yclxiao** [comment]
@chirag04 , can you tell me ,you fork github url?

**Comment by plrthink** [comment]
@yclxiao you can install via this url `"react-native-zip-archive": "plrthink/react-native-zip-archive#custom-ssziparchive"`

**Comment by plrthink** [comment]
I just published v2 to solve this issue. So pls update to that and I would close this issue. If you still have some problem around this, feel free to reopen this.

**Comment by Polidoro** [comment]
Just a heads up for anyone else trying to get this working, v2.0.0 did fix this issue for me, but I had to unlink and relink the RNZipArchive library in Xcode, then run a clean before it started working.

Thanks for the fix!

**Comment by itchingpixels** [comment]
Hey! We're trying to also use react-native-zip-archive with code push and bumping into another issue:

It seems like now that both react-native-zip-archive and codepush includes ssziparchive, some of the code won't compile because of duplicate struct definitions.

![image](https://user-images.githubusercontent.com/5416288/31835819-f43df960-b5ca-11e7-9b18-70aeafa3e67d.png)

**Comment by pedrosimao** [comment]
The issue still hasn't been resolved?
