### ISSUE TITLE
Path Traversal vulnerability: Security Alert Received on Google Play Console

### ISSUE THREAD

**Issue by ammarahm-ed** [mockingbot/react-native-zip-archive#170]
We recently recieved the following warning on google play developer console:

Security alert
Your app contains an unsafe unzipping pattern that may lead to a Path Traversal vulnerability. Please see this Google Help Center article to learn how to fix the issue.
Vulnerable locations:

`com.rnziparchive.RNZipArchiveModule$2.run`
https://support.google.com/faqs/answer/9294009

react-native-zip-archive: 4.1.3
react-native: 0.59.9

Here is the part of code I am using to unzip subtitles from opensubtitles.org

```
loadSubtitle(id, url) {
    let dirs = RNFetchBlob.fs.dirs
    RNFetchBlob
      .config({

        path: dirs.SDCardDir + '/SUBS_FOLDER/' + id + "/" + id + ".zip"
      })
      .fetch('GET', url, {
        //some headers ..
      })
      .then((res) => {
        unzip(res.path(), dirs.SDCardDir + '/SUBS_FOLDER/' + id + "/").then(path => {

          RNFetchBlob.fs.ls(path).then(list => {

            list.forEach(async item => {

              let word = item.toLowerCase();
              if (await word.includes("srt") === true) {
                this.readTextFile(dirs.SDCardDir + '/SUBS_FOLDER/' + id + "/" + item)
              }
            })


          })
        })


      })
  }
```

**Comment by learnyst** [comment]
We are also getting this warning.

**Comment by plrthink** [comment]
I'm working on this but actually have no idea since we do prevent this problem in [these lines of code](https://github.com/mockingbot/react-native-zip-archive/blob/master/android/src/main/java/com/rnziparchive/RNZipArchiveModule.java#L475) and also passed the test with the file in [this repo](https://github.com/snyk/zip-slip-vulnerability/tree/master/archives). It would be much appreciated if someone gives the instructions.

**Comment by thewisefarmerr** [comment]
Hello there, thank you for your reply, I think this problem is not related to path traversal, instead it appears when your app crashes on older versions of android before android 7.0. The reason for it is that older versions of android do not support `java.util.zip.ZipFile`. I think the library is unable to calculate the size of the zip file `getUncompressedSize(String zipFilePath, String charset)` in this method. Since I only needed plain unzipping, i had to make a simple module for unzipping and it works okay, also no warnings from google play. I think there should be a check for android version and it should skip uncompressed file size checking. On my newer android 9.0 lg g7 thinq this problem never occured with your library but on old android 6.0 huawei ShotX I was getting this problem.


I hope this information helps

**Comment by plrthink** [comment]
@thewisefarmerr thanks for your investigating, this would be much clear on what's going wrong here. I would fix this in this week.

**Comment by plrthink** [comment]
After digging into this I just remember that this actually getting fixed in the version 4.1.5 with this PR https://github.com/mockingbot/react-native-zip-archive/pull/168. So please try the 4.1.5 or higher to see whether it works or not.

**Comment by plrthink** [comment]
@SimonSimya 😂😂. Not really sure how Play Store checks for this issue. But I indeed test against the archive with the problem and it throws as expected. Maybe I need report this to the Play Store to see if there’s something we can do better.

**Comment by ZodiacGemini** [comment]
I know that this might be worked on already, but wanted to add that I'm also getting the warning on Google Play for both apps I have published. Both using version 5.0.0.
Have you gotten any more information about what the issue might be :)?

**Comment by learnyst** [comment]
We have submitted the app to play store with latest version. Still the issue exists

**Comment by plrthink** [comment]
Still has no idea by myself. The next step is contacting Google Play to ask for help.

But I'm currently on the vacation so don't have enough time to dig into. Already mark this as the Highest Priority and will continue to work on this when coming back.

**Comment by SDxBacon** [comment]
The warning from Google Play Console shows that the vulnerability is detected from `com.rnziparchive.RNZipArchiveModule$2.run`. However, all of unzip API that provided in this library have already guarded by running `ensureZipPathSafety()` method. The only `run()` method of a `Runnable` instance that is not executing `ensureZipPathSafety()` is inside `processZip()` method.

Thus, I try to make a small change and commit on my fork [here](https://github.com/SDxBacon/react-native-zip-archive/commit/f7b8beb5031651b2f37eabb297a28bdaf1786c26#diff-3b04f14dfe85c632b33626349cba3878R380). Currently, I have not received the same warning from Google Play Store yet.

**Comment by plrthink** [comment]
@SDxBacon Cool, but dont have time to review it now, would do that ASAP.

It's totally fine to open a PR about this which would also bring others in to improve your solution.

**Comment by plrthink** [comment]
@SDxBacon Yes, that could be a reason. Maybe we should check for it at any level of the folders. 

I do send the email for the details of the issue to the Google Play Console but with no responses. Really wish we could find the test cases(maybe it is opened somewhere?) then we would clearly know how to fix this.

**Comment by StanislavMayorov** [comment]
We get the same alert for version 2.2.6 which isn't used in the project at all. It was only installed.

**Comment by anastely** [comment]
I faced the same issue with V5.0.0!
any updates Guys, My client wanna kill me 😂😂

**Comment by anastely** [comment]
@plrthink

Here's a link from Google for this issue
https://support.google.com/faqs/answer/9294009

**Comment by ammarahm-ed** [comment]
@anastely on which android version are you getting this error? any idea?

**Comment by anastely** [comment]
@ammarahm-ed
 I have android 8 and it's working fine, but this issue appears when I publish the app to Google Play Store!

**Comment by ammarahm-ed** [comment]
Basically I opened this issue a few months back and I had same problem as yours. For me this issue appeared only android 6.0 <  devices only. I had an android 8.0 and 9.0 device and it worked perfectly but when I put the app on playstore, somebody with older android downloaded my app, I got this security warning from google. Before unzipping this module tries to check the size of the zip file. Older Api do not support this feature maybe... But anyways I only needed unzipping, so i wrote a simple function and since then it has been working perfectly. I dont use this library anymore due to this issue. The Error Occurs due to crash when trying to unzip. If you dont believe me try using it in an emulator with api 23 or lower and it will crash when file is unzipped.

**Comment by anastely** [comment]
hmm, yeah I believe you :) So to publish my app should remove this library from my dependency :(?  , And whats function you used?

**Comment by ammarahm-ed** [comment]
If the developer does not fix this, there wont be any other option left than removing the library as I did. 

[unzipModule.zip](https://github.com/mockingbot/react-native-zip-archive/files/4117416/unzipModule.zip)

Extract the files from zip folder and put them in the following folder along with your MainActivity.java & MainApplication.java

`android/app/src/main/java/`

Open each RNUnzipModule.java & RNUnzipPackage.java & edit the first import line and change it to your own application package name.

and then in your MainApplication.java add this: 


```java
 @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
    ++  packages.add(  new RNUnzipPackage());
      return packages;
    }
```

only add the line with ++.

If you are using react native 0.59 < then you will have to google yourself how to add native module in MainApplication.java.

Now on the JS side, where ever you want to use the module. simple import the following

```jsx
import {NativeModules} from "react-native"

// and create a const with that module.

const zip = NativeModules.RNUNzip;

```

Now to use its very simple:

```jsx
zip.unzip(yourZipFilePath, PathOfResultingUnzippedFile).then(path => {

console.log(path);
// do what you want here.
}
```

**Comment by anastely** [comment]
sadly i got this after calling unzip

Error: Couldn't unzip.
    at Object.fn [as unzip] (NativeModules.js:99)

**Comment by ammarahm-ed** [comment]
Do you have read and write permissions? please recheck. Also the function is working but for some unknown reason it is unable to unzip the file you provided to it so it is rejecting the promise. what are you trying to unzip?

**Comment by anastely** [comment]
Yes I Access to permissions , If i understand you well I want to unzip the file that contains pdf files

**Comment by ammarahm-ed** [comment]
Firstly I forgot to tell you this, the function I wrote was only for android & not ios so it wont work on ios, you will have to do your own research to find one. 

I used this function to unzip  zipped subtitle files on android. You are doing it right, i still dont understand why it is not working.  I will test it myself and see if it works for me. btw try to replace RNFS.ExternalStorageDirectoryPath to 'file:///storage/emulated/0/Pdf_app/allvalues.zip' 

I will check and see why it might not be working.

**Comment by anastely** [comment]
Thank you, it's work after uninstalling the and re-build app again without replacing `RNFS.ExternalStorageDirectoryPath` I don't know why 😬, So maybe you should make it as a package for other users still having this issue, it will be helpful 🔥

**Comment by ammarahm-ed** [comment]
Thats great. I hope your issue will be fixed on google play too once you upload the new version.

**Comment by moweex-mobile** [comment]
@plrthink  same issue with latest version 5.0.0
Please can you solve this problem ASAP....

![Screen Shot 2020-01-29 at 4 06 15 PM](https://user-images.githubusercontent.com/56818655/73363547-9da98a80-42b1-11ea-83cd-4bb79d851732.png)

**Comment by ammarahm-ed** [comment]
@moweex-mobile until the problem is fixed by the developer you can use my module i provided above for simple unzipping only on android.on which android version are you getting this error?? Check your Crashes on Google Play Console.

**Comment by plrthink** [comment]
@moweex-mobile can you try the version 5.1.0-dev.0 to see whether this problem is getting fixed?

**Comment by plrthink** [comment]
@ammarahm-ed I see you're saying you got some crashes due to ZipFile is not supported by the older version of Android. But the doc https://developer.android.com/reference/java/util/zip/ZipFile states it's introduced in the API Level 1 which means it should work on all Android dists. And I also checked on the Android 5 which works as expected.

So I think the ZipFile is irrelevant to this issue. Could you see the backtrace of the crash? Maybe there're some other problems.

And recently I find the fix mentioned by this issue https://github.com/srikanth-lingala/zip4j/issues/133 of the zip4j, the project also used partially in this package, to deal the same issue we got from the Google Play. So I just stole that and published a beta version 5.1.0-dev.0 to try to fix.

**Comment by ammarahm-ed** [comment]
@plrthink the problem is that nobody properly shared the stacktrace or a crash report from google play. This leads to alot of confusion for the developer. I hope the issue is fixed as you are saying. I will also test the dev version and see if i get the error or not.

**Comment by plrthink** [comment]
@ammarahm-ed I guess this problem is a warning that emitted as soon as uploading the new version of the app to Google Play, which is part of the tests triggered by Google Play, rather than a runtime error on the user side. So others may not have the error stack.

**Comment by moweex-mobile** [comment]
@ammarahm-ed Thnx, i will try  
@plrthink Same security alert using "5.1.0-dev.0", any idea how to solve it ?

**Comment by plrthink** [comment]
very sad to hear this... 

almost tried the solutions out the internet but without a success. would still searching for.

**Comment by plrthink** [comment]
already using the suggested code from https://snyk.io/research/zip-slip-vulnerability#java, see https://github.com/mockingbot/react-native-zip-archive/blob/d73ee7976535b72c7aaf73ec0eac9467455e8c8d/android/src/main/java/com/rnziparchive/RNZipArchiveModule.java#L475

**Comment by moweex-mobile** [comment]
@plrthink ensureZipPathSafety doesn't throw any exception but playStore still show the warning.
Any updates ????

**Comment by plrthink** [comment]
@moweex-mobile could you show the file you're trying to unzip? maybe I can find the issues from there. I have tested with the files from https://github.com/snyk/zip-slip-vulnerability/tree/master/archives with the exception thrown.

**Comment by moweex-mobile** [comment]
@plrthink solved the problem by the following steps:

1. Delete "ensureZipPathSafety" method, Duplicate its logic inside each **RUN** thread where it was called 
( methods =>  unzipWithPassword, unzip, unzipAssets ).
2. Use **SecurityException** instead of normal Exception.

It seems that Google Play Store tools validate on code within **RUN** thread ONLY ignoring any called method.

I made a pull request which contains those changes [https://github.com/mockingbot/react-native-zip-archive/pull/187](url)

**Comment by plrthink** [comment]
@moweex-mobile Cool!! But it's ridiculous for Google Play...

**Comment by plrthink** [comment]
Hi folks here, can you try the version 5.1.0-beta.1? Which using @moweex-mobile's patch to fix this.

**Comment by plrthink** [comment]
@anastely can you the version 5.1.0-beta.1 to verify the solution? Thank you in advance.

**Comment by plrthink** [comment]
Ok, finally I just published version 5.0.1 to address this using @moweex-mobile's solution. Please let me know if the issue still exists.

**Comment by acostalima** [comment]
@plrthink I will give it a shot and get back to you soon!

**Comment by anastely** [comment]
@acostalima any updates?

**Comment by plrthink** [comment]
@anastely does 5.0.1 solve you problem?

**Comment by anastely** [comment]
@plrthink sadly not tested it yet, because I can't access to the client these times to get the google play account:(

**Comment by acostalima** [comment]
@anastely @plrthink sorry for the delay! I've recently published the app with your changes and the security alert is gone now. Thanks! 💪

**Comment by plrthink** [comment]
@acostalima Good to hear this, also I have published the regular version 5.1.0 which you could upgrade to.

**Comment by adamgins** [comment]
Hi, I still seem to be getting this issue with `"react-native-zip-archive": "5.0.2"` any ideas?

**Comment by acostalima** [comment]
> Hi, I still seem to be getting this issue with `"react-native-zip-archive": "5.0.2"` any ideas?

It takes sometime got Google Play Console to refresh apps' status. Is the security alert still in effect?

**Comment by vishalneogit** [comment]
I am still getting the issue.
I tried installing following version of the module:
1. **5.1.0-dev.0**
2. **5.0.2**: 
3. **5.0.0**

**Comment by acostalima** [comment]
One more thing: as far as I remember, you have to release your app to production in order to refresh its status. It's not enough to release it to the Internal Test Track or a Closed Track.

**Comment by vishalneogit** [comment]
> One more thing: as far as I remember, you have to release your app to production in order to refresh its status. It's not enough to release it to the Internal Test Track or a Closed Track.

Yes, This issue is generated only on production mode.
And It takes one day at least to update the status on play store

**Comment by acostalima** [comment]
@vishalneogit the issue seems to be solved on my end, so I don't really know what's going on.

**Comment by vishalneogit** [comment]
> @vishalneogit the issue seems to be solved on my end, so I don't really know what's going on.

Oh okay.
@acostalima can you please tell which version of the library are you using?

**Comment by acostalima** [comment]
> > @vishalneogit the issue seems to be solved on my end, so I don't really know what's going on.
> 
> @acostalima can you please tell which version of the library are you using?

I'm using a patched version because of a very specific business requirement. However, I did patch the affected Java code and the warning went away.

**Comment by vishalneogit** [comment]
> > > @vishalneogit the issue seems to be solved on my end, so I don't really know what's going on.
> > 
> > 
> > @acostalima can you please tell which version of the library are you using?
> 
> I'm using a patched version because of a very specific business requirement. However, I did patch the affected Java code and the warning went away.

@acostalima @plrthink warning is now gone.
Version I used is **^5.1.0-beta.1**.
