### ISSUE TITLE
unzipAssets does not work on android platform.

### ISSUE THREAD

**Issue by xclidongbo** [mockingbot/react-native-zip-archive#173]
react-native-cli: 2.0.1
react-native: 0.59.10
"react-native-zip-archive": "4.1.5"

```
import RNFS from 'react-native-fs';
import {zip, unzip, unzipAssets, subscribe} from 'react-native-zip-archive';
......

let rootZipPath = 'app.zip';
let  documentPath = RNFS.ExternalCachesDirectoryPath+'/Documents';
if (true == await RNFS.existsAssets(rootZipPath)){
          try {
            await unzipAssets(rootZipPath, documentPath)
          } catch (error) {
            console.log(error);
          } 
        }
```

Error:
```
Error: Asset file `app.zip` could not be opened
    at createErrorFromErrorData (NativeModules.js:155)
    at NativeModules.js:104
    at MessageQueue.__invokeCallback (MessageQueue.js:414)
    at MessageQueue.js:127
    at MessageQueue.__guard (MessageQueue.js:314)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
    at debuggerWorker.js:80
```

**Comment by bimbox-open** [comment]
@xclidongbo Hi there! I found this error, too. I solved by this way: use method 'copyFileAssets' on [https://github.com/itinance/react-native-fs/](react-native-fs).
execute these below: (RNFS === react-native-fs)
Step1: RNFS.copyFileAssets(`${androidAssetsUri}`, `${targetPath}/tmp`)
Step2: unzip(`${targetPath}/tmp`, documentPath), 
Step3: RNFS.unlink(`${targetPath}/tmp`)

**Comment by xclidongbo** [comment]
@bimbox-open  Good job!

**Comment by plrthink** [comment]
This maybe caused by the permissions. I would take a look ASAP.

**Comment by bulby97** [comment]
@plrthink Any news regarding this ? I'm getting the same issues.

**Comment by plrthink** [comment]
@bulby97 sorry, no. But could you please try the tmp solution suggested by @xclidongbo ? And we would fix this maybe in the next release.

**Comment by irfana1716** [comment]
@bimbox-open Can you please confirm the androidAssetsUri in copyassetsfile. I am still getting a same error
