### ISSUE TITLE
Unzipping without free space. No error! Just hangs...

### ISSUE THREAD

**Issue by flashman2** [mockingbot/react-native-zip-archive#177]
I tried it with Downloads directory. When unzipping to a mobile storage without enough space, unzipping just hangs without any errors! I tried this with a big zip files and small amount of available free space for unzipping. App just hangs without any error.
Is there any way to throw an error if unzipping is unsuccessful because of reaching the limit of free space?

**Comment by plrthink** [comment]
Sorry, we think we haven't implemented this yet, but it's an essential feature, I'm interested to introduce this into the next release. 

Also, PRs are welcome!

**Comment by learnyst** [comment]
@plrthink This is important feature. When is next release planned?

**Comment by plrthink** [comment]
@learnyst I hope late this month

**Comment by learnyst** [comment]
ok..thannks

**Comment by sayem314** [comment]
Is this fixed?

**Comment by plrthink** [comment]
@sayem314 Sorry, this hasn't been implemented yet. But I'm planning to solve this month.

**Comment by magrinj** [comment]
@plrthink Is it actually shipped ?

**Comment by plrthink** [comment]
@magrinj No, I haven't find the time to implement this before, but maybe I can try to work on this. Hope I can fix this very soon.

**Comment by plrthink** [comment]
Hi, folks, are you all facing this issue on the Android platform?
