### ISSUE TITLE
react-native@0.59.9 & react-native-zip-archive : Cannot get property 'compileSdkVersion' 

### ISSUE THREAD

**Issue by tombombadilom** [mockingbot/react-native-zip-archive#180]
after a fresh install of react-native-zip-archive@4.1.5 in a project created by react-native-cli :+1: 
```
node_modules/react-native-zip-archive/android/build.gradle' line: 15

* What went wrong:
A problem occurred evaluating project ':react-native-zip-archive'.
> Cannot get property 'compileSdkVersion' on extra properties extension as it does not exist

```
I think the problem is that I don't have any ext in my android/build.gradle

```
buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    // Workaround for https://issuetracker.google.com/117900475
    // Remove when upgrading to AGP 3.4 or higher.
    configurations.matching { it.name == '_internal_aapt2_binary' }.all { config ->
        config.resolutionStrategy.eachDependency { details ->
            details.useVersion("3.5.0-alpha03-5252756")
        }
    }
    repositories {
        mavenLocal()
        maven {
            url 'https://maven.google.com/'
        }
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```
but I have one in android/app/build.gradle:
```
android {
    compileSdkVersion 28
    buildToolsVersion '28.0.3'
    flavorDimensions "platform"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.booksonwall"
        minSdkVersion 23
        targetSdkVersion 28
        multiDexEnabled true
        versionCode 1
        versionName "1.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
```

**Comment by plrthink** [comment]
Sorry for the late response.

Have you solved the problem? I just tested the package of 4.1.5 on react-native@0.59.9 and it works as 
. Can you try to run `react-native link` first?

**Comment by tombombadilom** [comment]
no I haven't solved it 
The react-native link is ok 
```
info Linking "react-native-zip-archive" iOS dependency
info iOS module "react-native-zip-archive" has been successfully linked
info Linking "react-native-zip-archive" Android dependency
info Android module "react-native-zip-archive" has been successfully linked
```
But when I try to compile , I still get :+1: 
`FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '../myproject/node_modules/react-native-zip-archive/android/build.gradle' line: 15

* What went wrong:
A problem occurred evaluating project ':react-native-zip-archive'.
> Cannot get property 'compileSdkVersion' on extra properties extension as it does not exist
`

**Comment by tombombadilom** [comment]
Here is a git diff when i install and link react-native-zip-archive in my project , maybe something went wrong
[diff.log](https://github.com/mockingbot/react-native-zip-archive/files/4315472/diff.log)

**Comment by plrthink** [comment]
After reviewing the info you provided above, I think the problem is you don't have the `ext` section in `android/build.gradle` like this https://github.com/mockingbot/react-native-zip-archive/blob/master/example/android/build.gradle#L4. You can follow the example app to fix this.

**Comment by tombombadilom** [comment]
Thanx it's what i thought , and thanx for howTo fix it !

**Comment by hokaiyipFS** [comment]
I have to add the following line to my RN 0.59.9 project build.gradle then it works

ext {
...
    minSdkVersion = 26 <--- you may have a different midSdkVersion. 
...
 }
