### ISSUE TITLE
Is it possible to unzip a folder?

### ISSUE THREAD

**Issue by ahmedreda97** [mockingbot/react-native-zip-archive#182]
It seems that i can't unzip a folder only one file, is that right?
I get this error: {FramesToPop: 1, code: "EUNSPECIFIED"}
Example:-
Folder1/Folder2/image.png

**Comment by plrthink** [comment]
which platform you are working on? Android or iOS?

**Comment by ahmedreda97** [comment]
> which platform you are working on? Android or iOS?

Android

**Comment by madhums** [comment]
I have the same question for iOS. I have [a zipped file](https://www.dropbox.com/s/a389a9djp4jvapu/tiles.zip?dl=0). When I try to unzip it, I get this error saying: 

<summary>Error: failed to open zip file 
<details><pre>Error: failed to open zip file
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:99:50 in fn
- node_modules/react-native-zip-archive/index.js:12:60 in unzip
* app/screens/Task.js:49:38 in <anonymous>
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:271:30 in invoke
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:135:28 in invoke
- node_modules/regenerator-runtime/runtime.js:145:19 in Promise.resolve.then$argument_0
- node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
- node_modules/promise/setimmediate/core.js:123:25 in setImmediate$argument_0
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:146:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:194:17 in _callImmediatesPass
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:458:30 in callImmediates
* [native code]:null in callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:407:6 in __callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:143:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:142:17 in __guard$argument_0
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue
</pre></details>
</summary

**Comment by madhums** [comment]
First I ran into this issue https://github.com/mockingbot/react-native-zip-archive/issues/152 after fixing that it seems to work.

**Comment by plrthink** [comment]
@ahmedreda97 can you try the solution on the issue #152 as @macrozone pointed out?

**Comment by plrthink** [comment]
Have you fixed this problem?

**Comment by gilshaan** [comment]
Yes, it is possible to unzip a folder.

**Comment by vinayn-simelabs** [comment]
How can I zip a text file or pdf file. I'm getting the same issue while zipping a file in Android and iOS @plrthink
