### ISSUE TITLE
Error: File or folder does not exist (Android)

### ISSUE THREAD

**Issue by Hassaan68** [mockingbot/react-native-zip-archive#188]
i have created target zip file and then i passed source folder path and target Path to zip method and found an error.

**Comment by plrthink** [comment]
Can you show the code you're using？Also you can navigate in the file system using `adb shell`(Android) or just the regular fs operations (iOS) to verify the missing file.

**Comment by plrthink** [comment]
This may be the issue with https://github.com/mockingbot/react-native-zip-archive/issues/199 and should be fixed in 5.0.3, you can try that version. Feel free to reopen this if your problem still exists.
