### ISSUE TITLE
The module cannot pod install

### ISSUE THREAD

**Issue by eeee2222345** [mockingbot/react-native-zip-archive#191]
I refer the guide to operate, but I can not process command "pod install".
The terminal return "[!] No `Podfile' found in the project directory."
My react-native version is 0.57.8.

My project can build successful at Android and iOS if I ignore the error.
The unzip command can work at Android. If I run at iOS, the Xcode will log error "TypeError: undefined is not an object (evaluating 'RNZipArchive.unzip')".

How can I resolve this problem?

**Comment by plrthink** [comment]
Sorry for miss leading in the doc, you should follow the guide of the version 4.x for linking  https://github.com/mockingbot/react-native-zip-archive/tree/4.1.5, the current README is for version above 4.x.

**Comment by eeee2222345** [comment]
Thank!

The link is effective for me.
Due to my react-native version is 0.57.8, the installation command follows:
`npm install --save react-native-zip-archive@3.0.1`
`react-native link react-native-zip-archive`
to install automatically.


But the Xcode will log error "TypeError: undefined is not an object (evaluating 'RNZipArchive.unzip')" too.
So I manually link ios again. Follows: step2
[https://reactnative.dev/docs/linking-libraries-ios.html#step-2-1](https://reactnative.dev/docs/linking-libraries-ios.html#step-2-1)

I can execute my project now!
