### ISSUE TITLE
Invariant Violation: Native module cannot be null

### ISSUE THREAD

**Issue by afonseca95** [mockingbot/react-native-zip-archive#195]
I follow all steps for use, but when I add:
import { zip, unzip, unzipAssets, subscribe } from 'react-native-zip-archive'
show this massage, why? Thanks!!
<img width="405" alt="Screen Shot 2020-03-19 at 6 43 20 AM" src="https://user-images.githubusercontent.com/61551871/77068983-2b018500-69ad-11ea-8f41-b8c0921a6ffa.png">

**Comment by plrthink** [comment]
It seems like the problem is caused by the app code,  as you can see in the error - `state.global`. I think it means the `state` is `undefined` as the time of execution.

**Comment by afonseca95** [comment]
> It seems like the problem is caused by the app code, as you can see in the error - `state.global`. I think it means the `state` is `undefined` as the time of execution.

Sorry I add a wrong Image, this is the correct
<img width="405" alt="Screen Shot 2020-03-19 at 6 43 20 AM" src="https://user-images.githubusercontent.com/61551871/77068884-02798b00-69ad-11ea-8c2f-804f18d1021e.png">

**Comment by afonseca95** [comment]
> It seems like the problem is caused by the app code, as you can see in the error - `state.global`. I think it means the `state` is `undefined` as the time of execution.

Sorry was a wrong image, now is correct, maybe can you help me , thanks.

**Comment by plrthink** [comment]
Ok, here we go. And this error is simply telling you haven't linked the module successfully. Depending on your react-native version and react-native-zip-archive version, the solutions vary.

So first please check the versions you're using, they should be matched each other as described in this table https://github.com/mockingbot/react-native-zip-archive#compatibility.

And for the react-native >= to 60, you should follow the instructions here https://github.com/mockingbot/react-native-zip-archive#linking to get the linking done.

As for react-native < 60, you should check this out https://github.com/mockingbot/react-native-zip-archive/tree/4.1.5#linking.

Also if things still not working, please refer to the official dos about linking https://reactnative.dev/docs/linking-libraries-ios. Remember to switch to the right version you're using on the top left.

**Comment by afonseca95** [comment]
I have downgradle the library version to 5.0.1 and it no longer shows the error when importing the library, but now it shows this message:
I am using :
    "react": "16.9.0",
    "react-native": "0.61.4",
    "react-native-zip-archive": "^5.0.1",
<img width="443" alt="Screen Shot 2020-03-19 at 3 34 47 PM" src="https://user-images.githubusercontent.com/61551871/77117242-3a0d2500-69f7-11ea-9c8a-e591786bfe3d.png">

**Comment by plrthink** [comment]
Could you provide a minimal repo to reproduce this error? That would be helpful.

**Comment by anforu** [comment]
> Could you provide a minimal repo to reproduce this error? That would be helpful.

Morning @plrthink , Sorry for the late reply, I created the example repository, the example is extremely short, it only contains a "Hello world" and it has the library: "react-native-zip-archive": "^ 5.0.2", it has the version 5.0.1, since it does not show an error when importing the library as in 5.0.2.
I very much add the help in this problem that I am having, thank you very much.

Its the repository with the example: 
https://github.com/anforu/zipExample.git

**Comment by plrthink** [comment]
@anforu I just opened a pull request to fix this, and you see the details over here.

**Comment by afonseca95** [comment]
Hi @plrthink  , I have another problem, is when I used "unzip" show this message : Error to unzip file [Error: failed to open zip file], the method Zip is working but the unzip not.
What could it be? The example of methods are in my repository https://github.com/anforu/zipExample.git 
also is the code : 

/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React, { Component } from 'react'
import { View, Text } from 'react-native';

import { zip, unzip } from 'react-native-zip-archive'

import { DocumentDirectoryPath } from 'react-native-fs'

const targetPath = `${DocumentDirectoryPath}/myFile.zip`
const sourcePath = DocumentDirectoryPath


export default class App extends Component {
  constructor(props) {
    super(props)
    this.compessZipFile()
    this.decompessZipFile()
  }
  compessZipFile = () => {
    console.log('TargetPath:', targetPath)
    zip(sourcePath, targetPath)
      .then((path) => {
        console.log(`zip completed at ${path}`)
        //this.decompessZipFile()
      })
      .catch((error) => {
        console.log('Error to try to decompess file', error)
      })
  }

  decompessZipFile = () => {
    unzip(sourcePath, targetPath )//with unzip(targetPath, sourcePath) show success but does not show any changes to the file
      .then((path) => {
        console.log(`unzip completed at ${path}`)
      })
      .catch((error) => {
        console.log('Error to unzip file',error)
      })
  }
  render(){
  return (
    <View >
      <Text > Hello, world!</Text>
    </View>
  )
}
}

Thanks such much for your time and your help.

**Comment by plrthink** [comment]
Have inspected on your example and find that you should unzip the file to another new place, like the PR I opened 👉 https://github.com/anforu/zipExample/pull/2. And once you get this done, you could use the `adb shell` to navigate around the file system of your android emulator, here is the structure I have tested against. You can see the `new_files` folder is the exact same thing as the `files`, where I compressed before.

```sh
generic_x86:/data/user/0/com.zipexample/files # pwd
/data/user/0/com.zipexample/files
generic_x86:/data/user/0/com.zipexample/files # ls -al
total 4164
drwxrwx--x 3 u0_a130 u0_a130    4096 2020-05-06 13:02 .
drwx------ 9 u0_a130 u0_a130    4096 2020-05-06 12:57 ..
-rw------- 1 u0_a130 u0_a130 3609386 2020-05-06 12:58 ReactNativeDevBundle.js
-rw------- 1 u0_a130 u0_a130  616789 2020-05-06 13:02 myFile.zip
drwx------ 2 u0_a130 u0_a130    4096 2020-05-06 13:02 new_files
generic_x86:/data/user/0/com.zipexample/files # cd new_files/
generic_x86:/data/user/0/com.zipexample/files/new_files # ls -al
total 3548
drwx------ 2 u0_a130 u0_a130    4096 2020-05-06 13:02 .
drwxrwx--x 3 u0_a130 u0_a130    4096 2020-05-06 13:02 ..
-rw------- 1 u0_a130 u0_a130 3609386 2020-05-06 13:02 ReactNativeDevBundle.js
generic_x86:/data/user/0/com.zipexample/files/new_files #
```
