### ISSUE TITLE
Unzip error: Couldn't open file

### ISSUE THREAD

**Issue by yosikal** [mockingbot/react-native-zip-archive#199]
Trying to unzip zip file on Android I encounter an error "Couldn't open file".  I verified the file exists in two ways: 
1. Manually browsing by using adb shell 

2. Using expo file system FileSystem.getInfoAsync right before calling unzip. As you can see in the following getInfoAsync returns info on the file and right afterwards unzip fails:

 LOG  {"exists": true, "isDirectory": false, "modificationTime": 1585666338, "si
ze": 31541279, "uri": "file:///data/user/0/com.visitacityapp/files/tmp/myFile2.z
ip"}
 LOG  unzip
 LOG  [Error: Couldn't open file file:///data/user/0/com.visitacityapp/files/tmp
/myFile2.zip. ]

**Comment by yosikal** [comment]
I'm not sure if that's a bug what once removed the "file://" prefix unzip works fine.

**Comment by plrthink** [comment]
Fixed in 5.0.3.
