### ISSUE TITLE
Annoying notifications in dev settings (and in packager as well) via this library on RN 0.62

### ISSUE THREAD

**Issue by gigby** [mockingbot/react-native-zip-archive#200]
**Describe the bug**
Annoying notifications in dev settings (and in packager as well) via this library on RN 0.62

**To Reproduce**
1. unzip any file with no listener
2. see packager console or thousands of yellow boxes in dev settings

**Expected behavior**
No messages should be sent (bcz the listener isn't required thing)

**Env (please complete the following information):**
 - Device: [iPhone6]
 - OS: [iOS12.4.4]
 - OS Version: [16G140]
 - Package Version: [5.0.1]

**Comment by plrthink** [comment]
I don't get the logs you mentioned, can you provide a screenshot to demo it?

**Comment by sunnylqm** [comment]
![image](https://user-images.githubusercontent.com/615282/83385005-fbdea980-a41a-11ea-92f8-a4cdd63281bb.png)

**Comment by plrthink** [comment]
I find this thread https://github.com/transistorsoft/react-native-background-geolocation/issues/242#issuecomment-302110026 discusses this problem which says we can't turn that off from the library.

**Comment by sunnylqm** [comment]
@plrthink  https://reactnative.dev/docs/native-modules-ios#optimizing-for-zero-listeners

**Comment by plrthink** [comment]
Cool, this is exactly what we need. Would fix this this week.

**Comment by plrthink** [comment]
solved in #212
