### ISSUE TITLE
[ERROR] Cannot use import statement outside module

### ISSUE THREAD

**Issue by srikanthsunkari** [mockingbot/react-native-zip-archive#203]
I am trying to execute the [sample](https://github.com/plrthink/RNZATestApp) application, While launching the application I am running into the below error.

**To Reproduce**
1. Running react-native run-ios will produce this. OR launching app will do it.

And Metro bundler builds 100% successfully.

**Expected behavior**
App should be launched successfully and testable.

**Env :**
 - Device: iPhone X 
 - OS: iOS12.1
 - OS Version: 10.13.6
 - Package Version: ^5.0.0

**Additional context**
Getting this below error,
IN DEVELOPER MODE ON
![Simulator Screen Shot - iPhone X - 2020-05-21 at 13 46 39](https://user-images.githubusercontent.com/8381508/82554198-1e530600-9b83-11ea-9958-3aa945e9fd8f.png)

IN DEVELOPER MODE OFF
![Simulator Screen Shot - iPhone X - 2020-05-21 at 16 50 40](https://user-images.githubusercontent.com/8381508/82554338-59edd000-9b83-11ea-8caf-20a21d4ac1f7.png)

**Comment by plrthink** [comment]
You can use `yarn run haul` to start the app, and yes, the `start` command failed to compile the source.

**Comment by plrthink** [comment]
Just update the [readme](https://github.com/plrthink/RNZATestApp/blob/develop/package.json) to emphasize the process of the up and running. So I'm going to close this issue.
