### ISSUE TITLE
Error: Failed to extract file Found Zip Path Transversal Vulnerability with /data/data/com.example.example/files/filesUnzip

### ISSUE THREAD

**Issue by jersonpl** [mockingbot/react-native-zip-archive#205]
Error unzip

![Screenshot_1591258471](https://user-images.githubusercontent.com/39785621/83732901-5a21ad00-a612-11ea-9d10-bf38a62c450a.png)

 - Device: android emulator
 - OS: android
 - OS Version: all
 - Package Version: 5.0.2

**Comment by chiefchief** [comment]
@jersonpl have you find solution?
