### ISSUE TITLE
Suport for RAR formats

### ISSUE THREAD

**Issue by rubengarciam** [mockingbot/react-native-zip-archive#21]
Have you considered extending react-native-zip-archive to rar files? I've been trying to use [Unrar4iOS](https://github.com/ararog/Unrar4iOS) and [UnrarKit](https://github.com/abbeycode/UnrarKit) via native function exports but couldn't make it work.

Btw, great work on the library so far :)

**Comment by plrthink** [comment]
Not using RAR files in my use cases actually, so I'm not sure how to deal with that.

And also I'm not sure whether it would be ok to supporting that in a single package, but I'm open with that.

We can seek help from the community.

**Comment by valery-lavrik** [comment]
Good afternoon! how are things with this issue today?

Can you recommend an analogue to solve this problem? Everything I don't try doesn't work (((

**Comment by plrthink** [comment]
Sorry for the late response, we're still not planning on this feature, and also haven't investigated how to implement this.

But open for OSS contribution.
