### ISSUE TITLE
Cannot build on iOS (SSZipArchive)

### ISSUE THREAD

**Issue by AndrewE1234** [mockingbot/react-native-zip-archive#219]
**Describe the bug**
I added this package to my react-native init app and it was no longer able to build and run on the iOS simulator. When running `react-native run-ios` (after correctly linking the package with pod install), the build would fail just a few seconds in, exiting with`error code 65` and citing this as the issue:

```
CompileC [path to project]/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SSZipArchive.build/Objects-normal/x86_64/mz_zip_rw.o 
[path to project]/ios/Pods/SSZipArchive/SSZipArchive/minizip/mz_zip_rw.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

I opened up the app's `.xcworkspace` and found 3 issues pertaining to the file `mz_zip_rw.c` in SSZipArchive, all of which reading `Incomplete definition of type 'struct dirent'` starting on line 1805. Attempting to build the project from the workspace also failed.

I made a new react-native init project, downloaded and linked the package via `npm` and `pod install` and simply imported it at the top of the `App.js` file and the issue still came up with all of the same problems listed above. However, since I had metro still running when I installed the package, it provided me with another error in which it seems to be unable to find a "main" module (see code block in additional content section bellow). Thank you!

**To Reproduce**
1. Create or open a react-native init project
2. Run `react-native run-ios` in the root directory
3. If the build fails, open up [myproject].xcworkspace and view any potential issues

**Expected behavior**
Should build without errors.

**Env (please complete the following information):**
 - Device: iPhone 11 (Simulator)
 - OS: iOS 13.1
 - OS Version: 13.1
 - MacOS Version: 10.15.6
 - Xcode Version: 11.1
 - Package Version: 5.0.6

**Additional context**
Screen shot of `SSZipArchive/mz_zip_rw.c`:

![Screen Shot 2020-10-01 at 1 42 31 PM](https://user-images.githubusercontent.com/27866821/94862552-02435900-03ee-11eb-8c18-71bcbac90212.png)

Metro error:
```
[Error: InternalError Metro has encountered an error: While trying to resolve module `react-native-zip-archive` from file
`[path to project]/App.js`, the package `[path to project]/node_modules/react-native-zip-archive/package.json` was 
successfully found. However, this package itself specifies a `main` module field that could not be resolved 
(`[path to project]/node_modules/react-native-zip-archive/index.js`. Indeed, none of these files exist:

  * [path to project]/node_modules/react-native-zip-
archive/index.js(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * [path to project]/node_modules/react-native-zip-
archive/index.js/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)]
```

**Comment by plrthink** [comment]
I just tried that but can't get the issue popup, same setup but I'm using the XCode 12.0.1. Can you provide the app has the issue you described?

**Comment by AndrewE1234** [comment]
I updated to Xcode 12.0.1 which seemingly fixed the issue. I am also using iOS 14, but based on your previous comment, it seems like using Xcode 12 instead of 11 did the trick. 

I was using a different and more "temperamental" machine when I raised the issue, so I unfortunately don't currently have access to the test program I created if you would still like to debug this issue. 

Thank you!

**Comment by plrthink** [comment]
Ok, I would tested with XCode 11 when possible, but I can't make a promise on this.

Thank you for your feedback. Stay safe.
