### ISSUE TITLE
Exception - Native module cannot be null

### ISSUE THREAD

**Issue by afikmenashe21** [mockingbot/react-native-zip-archive#220]
Hi,
I'm following the instructions, downloaded the library but when I try to run the project with the import of 'react-native-zip-archive' I got the Exception: `Native module cannot be null `
Everything went well, installed Cocoapods for Windows, Linked the libraries by `cd ./ios && pod install` 
Any idea to solve this issue, please? 
(Already tried this solution: https://github.com/mockingbot/react-native-zip-archive/issues/195 )
BTW, I'm using a Windows laptop and iPhone 11 trough Expo.

**Comment by plrthink** [comment]
Can you provide a minimal re-producible repo?

**Comment by afikmenashe21** [comment]
I will upload the project to the git in a minute

**Comment by afikmenashe21** [comment]
> Can you provide a minimal re-producible repo?

Here: https://github.com/afikmenashe21/WhatshareTest

**Comment by plrthink** [comment]
Did you eject from to bare workflow as described in the doc https://docs.expo.io/introduction/managed-vs-bare/#bare-workflow? It says if you want to use the native modules you need to do the ejection.

**Comment by afikmenashe21** [comment]
> Did you eject from to bare workflow as described in the doc https://docs.expo.io/introduction/managed-vs-bare/#bare-workflow? It says if you want to use the native modules you need to do the ejection.

I think I tried to do so in the past, anyway, I try to run `expo eject` and this is the result:
![image](https://user-images.githubusercontent.com/57488204/95685845-1c0d4900-0c03-11eb-9486-ec247490bbc5.png)

**Comment by plrthink** [comment]
ok, actually I'm not familiar with the expo, so it needs some time to dig into it.

**Comment by plrthink** [comment]
<img width="584" alt="Screen Shot 2020-10-12 at 2 26 17 PM" src="https://user-images.githubusercontent.com/2429369/95712372-3c86e300-0c97-11eb-8301-ed1b623c87da.png">
@afikmenashe21 Well, I can get it running successfully, so maybe there's something wrong with your setup. Maybe you can try to start from scratch.

**Comment by afikmenashe21** [comment]
> <img alt="Screen Shot 2020-10-12 at 2 26 17 PM" width="584" src="https://user-images.githubusercontent.com/2429369/95712372-3c86e300-0c97-11eb-8301-ed1b623c87da.png">
> 
> @afikmenashe21 Well, I can get it running successfully, so maybe there's something wrong with your setup. Maybe you can try to start from scratch.

First of all, I appreciate that.
Second, I just created a new project by expo init zipTest, then npm install react-native-zip-archive --save , wrote import { zip, unzip, unzipAssets, subscribe } from 'react-native-zip-archive' and once again Native module cannot be null.
This time i didn't linked by cd ios && pod install because i didn't run the command which creates the ios and android folders.

**Comment by plrthink** [comment]
As mentioned early, you should eject the expo project to let it play with the third party native modules.

**Comment by afikmenashe21** [comment]
> As mentioned early, you should eject the expo project to let it play with the third party native modules.

I tried to run `expo eject` and then cd ios && pod install, but still it doesn't work.

**Comment by plrthink** [comment]
I think it may be some issues with the Windows platform and personally, I'm working on the macOS. Can you try to install some other third party native libraries like react-native-fs?

**Comment by afikmenashe21** [comment]
> I think it may be some issues with the Windows platform and personally, I'm working on the macOS. Can you try to install some other third party native libraries like react-native-fs?

Same Exception, I have to mention that when I scan the QR code via android its all right, same result with `npm run web`.

**Comment by plrthink** [comment]
> > I think it may be some issues with the Windows platform and personally, I'm working on the macOS. Can you try to install some other third party native libraries like react-native-fs?
> 
> 
> 
> Same Exception, I have to mention that when I scan the QR code via android its all right, same result with `npm run web`.
> 
> 
Well, I think it's might related to the usage of the expo, since you said that it only works on android. So it would be better to ask in the expo community.

**Comment by afikmenashe21** [comment]
> Well, I think it's might related to the usage of the expo, since you said that it only works on android. So it would be better to ask in the expo community.

After a little digging, I figure out that with expo I can’t use packages with native languages that require linking and add native modules written in Objective-C, Swift, Java, Kotlin.
Which means I have to create a new project by vanilla react native.

**Comment by plrthink** [comment]
@afikmenashe21 I think it might be incorrect because I indeed can successfully run your app on the iOS emulator.

**Comment by plrthink** [comment]
I just closed the issue since it is not active for a time. But you can reopen it at any time if still suffer from this

And I think we should create an example to demonstrate how this module works with the expo. It would be great if someone wants to work on this.
