### ISSUE TITLE
unzip file size recommendation

### ISSUE THREAD

**Issue by vsalvans** [mockingbot/react-native-zip-archive#223]
I need to unzip big zip files that contain thousands of files.

In total I need to download 2GB, so I'm thinking to create chunks of files of 512MB,  download them and unzip them.

But I can choose any file size to suit the device resources.

In case of an iPad second generation with 4GB RAM, any recommendation what file size to choose?

I don't know how this package manages memory on big files. Is it like a stream so the file to unzip from can be as big as I want o is better to deal with smaller sizes?

Thanks!!

**Comment by plrthink** [comment]
Yes, `react-native-zip-archive` is using the `ZipArchive` under the hood for iOS, and it uses the stream to unzipping, as you can see https://github.com/ZipArchive/ZipArchive/issues/267. But I don't test it with such a large file actually.
