### ISSUE TITLE
Unzipping progress on iOS is not working correctly

### ISSUE THREAD

**Issue by jeffmon** [mockingbot/react-native-zip-archive#228]
When unzipping a file and subscribing to the progress, on iOS, it goes from `0` to `0.99997` almost instantly..then after 30 seconds later, it goes to `1`. On Android, it works beautifully, and as expected.

Here is my code: 

```
  useEffect(() => {
    const zipSubscribe = subscribe(({ progress, filePath }) => {
      setZipProgress(progress);
      return () => {
        zipSubscribe.remove();
      };
    });
  });
```

Shouldn't the progress on iOS behave the same as on Android? Going from `0` to `1` gradually until completion?

This happens on an iOS simulator and a physical iPhone device.

Using the latest stable version of `react-native`: `0.63.4`, and the latest version of `react-native-zip-archive`: `5.0.6`

Thanks in advanced!

**Comment by DavidGonzalezGutierrez** [comment]
In my case, with react-native: 0.63.4 and react-native-zip-archive: 5.0.6 on IOS in iphone 8 with ios 14, progress starts from 0.00010000 and decompress never ends.

With a very small zip of 10kb.
