### ISSUE TITLE
Header not found while unzipping the file with password.

### ISSUE THREAD

**Issue by Akash47** [mockingbot/react-native-zip-archive#229]
When unzipping a file with password it throws an exception saying headers not found. 

Here is the code:-
`const sourcePath = `${RNFS.ExternalStorageDirectoryPath }/download/offlineaadhaar20201222055348270.zip`
const targetPath = RNFS.ExternalStorageDirectoryPath 
const password = '4444'
 console.log(sourcePath)
unzipWithPassword(sourcePath, targetPath, password)
.then((path) => {
  console.log(`zip completed at ${path}`)
})
.catch((error) => {
  console.error(error)
})`

**Expected behavior**
A file is supposed to be unzipped and placed into the target folder.

**Env (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 11 

Here is the error which I am getting
```
[Error: Failed to unzip file, due to: net.lingala.zip4j.exception.ZipException: zip headers not found. probably not a zip file
        at net.lingala.zip4j.core.HeaderReader.readEndOfCentralDirectoryRecord(HeaderReader.java:122)
        at net.lingala.zip4j.core.HeaderReader.readAllHeaders(HeaderReader.java:78)
        at net.lingala.zip4j.core.ZipFile.readZipInfo(ZipFile.java:425)
        at net.lingala.zip4j.core.ZipFile.isEncrypted(ZipFile.java:722)
        at com.rnziparchive.RNZipArchiveModule$1.run(RNZipArchiveModule.java:75)
        at java.lang.Thread.run(Thread.java:76
```4)

**Comment by plrthink** [comment]
Can you provide the file that can reproduce the problem? That would be much helpful.

**Comment by Akash47** [comment]
I have send you that file via mail please check it once.

**Comment by plrthink** [comment]
@Akash47 Hi, I just tried the file you sent to me directly, and everything works as expected. I am using the emulator with Pixel 3a and Android 11 as you described.

What's the version of the package you're using?

````
generic_x86_arm:/data/user/0/com.rnzatestapp/files # pwd
/data/user/0/com.rnzatestapp/files
generic_x86_arm:/data/user/0/com.rnzatestapp/files # ls -al
total 3796
drwxrwx--x 2 u0_a161 u0_a161    4096 2021-01-06 12:37 .
drwx------ 9 u0_a161 u0_a161    4096 2021-01-06 12:28 ..
-rw------- 1 u0_a161 u0_a161 3851420 2020-12-01 15:19 ReactNativeDevBundle.js
-rw------- 1 u0_a161 u0_a161    7211 2020-12-29 11:34 file.ext
````

**Comment by Akash47** [comment]
Hi , I am using "5.0.6" version , can you share me the code so I will try
it once.

**Comment by plrthink** [comment]
Sorry for the late response, and you can check this branch https://github.com/plrthink/RNZATestApp/tree/rnza_issue_229.
