### ISSUE TITLE
iOS not zipping

### ISSUE THREAD

**Issue by sentry0** [mockingbot/react-native-zip-archive#230]
Not able to zip on iOS in simuation (xcode 12.3, iOS 14.3)

The file gets created but it looks like it's just a regular file with the characters "PK" in it.

`await zip(filePath, zipPath);`

I just caught the error `[Error: unable to zip]`... not much there to work with.

**Comment by sentry0** [comment]
Upgrading to 5.0.7-beta.3 had no effect

**Comment by plrthink** [comment]
Can you provide the whole error message? Also, it would be helpful if you can upload the zip file you're trying to zip.

**Comment by lh9403** [comment]
The same problem, and no error callbacks

**Comment by ramos-lucas** [comment]
The same problem and no error message. 
My file is a simple .txt with content 10 20 30

**Comment by ramos-lucas** [comment]
I managed to solve using `await zip([filePath], zipPath)`

**Comment by plrthink** [comment]
I would take a look at the interface `zip(source: string, target: string): Promise<string>`

**Comment by blakdragon39** [comment]
I'm also having running into this issue, but can't replicate it consistently. Been able to see it on iOS 14.3 and 14.4, simulators and real devices. No error gets thrown, it just fails silently. I was able to follow it as far as this line:

```RNZipArchive.zipFolder(normalizeFilePath(source), normalizeFilePath(target))```

**Comment by blakdragon39** [comment]
Further discovery, by accident, it is actually coming back with the error. But there was a 23-minute difference between when I started zip, and when the log came back.


```
[Tue Mar 23 2021 14:35:44.409]  LOG      SQLite.backgroundExecuteSqlBatch(<removed for brevity>)
[Tue Mar 23 2021 14:58:09.235]  ERROR    [Error: unable to zip]
```

**Comment by blakdragon39** [comment]
I was able to replicate the 23 minute wait! And it came back with a new error message
```{"error": {"code": "ENSCOCOAERRORDOMAIN0", "domain": "NSCocoaErrorDomain", "message": "Extension was interrupted", "nativeStackIOS": ["0   Hunchly                             0x000000010fed8757 RCTJSErrorFromCodeMessageAndNSError + 135", "1   Hunchly                             0x000000010fed8683 RCTJSErrorFromNSError + 275", "2   Hunchly                             0x000000010fe5f361 __41-[RCTModuleMethod processMethodSignature]_block_invoke_4.110 + 161", "3   Hunchly                             0x000000010fdb56de __48-[RNShare open:failureCallback:successCallback:]_block_invoke_2 + 206", "4   ShareSheet                          0x00007fff2db8e8c2 __68-[UIActivityViewController _cleanupActivityWithSuccess:items:error:]_block_invoke + 199", "5   ShareSheet                          0x00007fff2dbaf656 -[UIApplicationExtensionActivity _dismissActivityFromViewController:animated:completion:] + 244", "6   ShareSheet                          0x00007fff2db8df32 -[UIActivityViewController _performDismissWithSuccess:completionHandler:] + 617", "7   ShareSheet                          0x00007fff2db8e723 -[UIActivityViewController _cleanupActivityWithSuccess:items:error:] + 627", "8   ShareSheet                          0x00007fff2db91665 __45-[UIActivityViewController _performActivity:]_block_invoke + 121", "9   ShareSheet                          0x00007fff2db6e4fb -[UIActivity activityDidFinish:items:error:] + 99", "10  ShareSheet                          0x00007fff2dbaff91 __84-[UIApplicationExtensionActivity _instantiateExtensionViewControllerWithInputItems:]_block_invoke_2.136 + 234", "11  libdispatch.dylib                   0x00000001134c97ec _dispatch_call_block_and_release + 12", "12  libdispatch.dylib                   0x00000001134ca9c8 _dispatch_client_callout + 8", "13  libdispatch.dylib                   0x00000001134d8e75 _dispatch_main_queue_callback_4CF + 1152", "14  CoreFoundation                      0x00007fff2038edbb __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9", "15  CoreFoundation                      0x00007fff2038963e __CFRunLoopRun + 2685", "16  CoreFoundation                      0x00007fff203886d6 CFRunLoopRunSpecific + 567", "17  GraphicsServices                    0x00007fff2bededb3 GSEventRunModal + 139", "18  UIKitCore                           0x00007fff24690e0b -[UIApplication _run] + 912", "19  UIKitCore                           0x00007fff24695cbc UIApplicationMain + 101", "20  Hunchly                             0x000000010f8bf8f0 main + 112", "21  libdyld.dylib                       0x00007fff202593e9 start + 1", "22  ???                                 0x0000000000000001 0x0 + 1"], "userInfo": {"NSLocalizedDescription": "Extension was interrupted"}}}```

**Comment by blakdragon39** [comment]
It seems to have something to do with the name of the file being zipped too. However, this might also be device dependent. Zipping to a file named J.zip would cause my app to start erroring consistently. Whereas another person with a different phone could use J.zip, but couldn't use something called case.zip.

**Comment by plrthink** [comment]
@blakdragon39 It seems like a different problem with @ramos-lucas faced, but still has no idea about what happened, could you share the folder you want to zip?

**Comment by blakdragon39** [comment]
[J_original.zip](https://github.com/mockingbot/react-native-zip-archive/files/6198065/J_original.zip)
[J_2021-03-24T14_36_16.266Z.zip](https://github.com/mockingbot/react-native-zip-archive/files/6198066/J_2021-03-24T14_36_16.266Z.zip)

I've attached 2 files:
J_original is the original contents that I wanted to zip. (They've been zipped on my laptop.)

J_2021-03-24T14_36_16.266Z.zip was zipped by `react-native-sharing-archive`'s `zip` function. If I leave the zip file name as `J`, it hangs for over 20 minutes before finally erroring. So I added the date to the filename to get around that. However if you unzip that file, you'll find an invalid zip inside that zip file, so I believe something on iOS is getting zipped recursively. 

This same code works as expected on Android, with no issues.

**Comment by blakdragon39** [comment]
One other note, it doesn't seem to matter what the contents I'm trying to zip are. Changing the file name is what makes or breaks this. However the filename that breaks it seems to differ on devices.

**Comment by blakdragon39** [comment]
I've figured out what the problem is. I was putting the zip folder in the same folder that was being zipped. So the zip was being included in itself. I got around it by making a new path for the zip to go into. This doesn't seem to be an issue on android.

**Comment by esutton** [comment]
@ramos-lucas solution to wrap **filePath** in brackets fixed iOS problem where zip files were always empty ( 22 bytes long ).
```
await zip([filePath], zipPath)
```

Hopefully adding brackets does NOT break Android.  I had been using this library for years.  Both Android and IOS were zipping single files fine.  Not sure why iOS started breaking?

**Comment by esutton** [comment]
For the curious, the cause is the react-native-zip-archive index.js exports a single zip method, that uses the argument type to determine whether to call RNZipArchive.zipFiles or RNZipArchive.zipFolder.
```
export const zip = (source, target) => {
  return Array.isArray(source)
    ? RNZipArchive.zipFiles(source.map(normalizeFilePath), normalizeFilePath(target))
    : RNZipArchive.zipFolder(normalizeFilePath(source), normalizeFilePath(target));
};
```
On iOS, if you want to zip a file, always enclose the filePath argument in array brackets, else you may get an empty 22-byte zip file.
```
await zip([filePath], zipPath)
```
