### ISSUE TITLE
Unzipping causes 'crc check failed for file'

### ISSUE THREAD

**Issue by CDBridger** [mockingbot/react-native-zip-archive#232]
**Describe the bug**
Attempting to unzip a file causes 'crc check failed for file'

**To Reproduce**
1.Download .zip file
2.Attempt to unzip

**Expected behavior**
File unzips succesfully

**Env (please complete the following information):**
 - Device: iPad Air
 - OS: iOS 12.5.1
 - Package Version: 5.0.6

**Additional context**
Unzipping the file works on simulator, on mac etc, just not on iPad

**Comment by tempius** [comment]
I have this same error, but on iOS simulator.

**Comment by KhoaN56** [comment]
Has anyone have any idea to fix this error? I also have this issue on iOS simulator.

**Comment by MarotiKathoke** [comment]
Error: crc check failed for file.  i am still getting 6.1.0  in real ios device
