### ISSUE TITLE
What encryptionType used on iOS?

### ISSUE THREAD

**Issue by olosegres** [mockingbot/react-native-zip-archive#242]
Hi, encryptionType for iOS marked as not supported, but what type actually used? (If used default, so what does it mean STANDARD?)

**Comment by plrthink** [comment]
On iOS, the package is using SSZipArchive https://github.com/ZipArchive/ZipArchive under the hood, so I think we're using the zlib algorithm.

**Comment by olosegres** [comment]
Thanks!
