### ISSUE TITLE
duplicate symbol __zipOpenEntry

### ISSUE THREAD

**Issue by dieseldjango** [mockingbot/react-native-zip-archive#245]
In https://github.com/mockingbot/react-native-zip-archive/pull/47 a change was made to the SSZipArchive pod subspec to avoid a duplicate symbol conflict with CodePush. For some reason this was removed in a later version. I have a different framework I'm working with that also uses SSZipArchive and with the current react-native-zip-archive I get that same conflict.

Is there a reason that subspec was removed? I'm not an expert in pod dev, so if there's a straightforward workaround please let me know.

**Comment by plrthink** [comment]
It now uses cocoapod to manage the SSZipArchive, so it would work out of the box if the library you mention is also doing it in this way. 

Before RN embraces the cocoapod to manage native deps on iOS, we need to include the SSZipArchive's source code. That is also the reason why we get into conflict.

**Comment by dieseldjango** [comment]
Got it. Thanks for the information. Looks like the other framework I'm linking embeds the source code, causing the conflict.
