### ISSUE TITLE
Error: Failed to extract file error in opening zip file

### ISSUE THREAD

**Issue by valery-lavrik** [mockingbot/react-native-zip-archive#254]
"react-native": "0.66.4",
"react-native-zip-archive": "^6.0.6",
"rn-fetch-blob": "^0.12.0"

`	
let UNZIP_RES = false;
try {
	UNZIP_RES = await unzip(CBR.fileCopyUri, CBR_DIR);
} catch (error) {
	console.log(error);
}
`

Error:   **LOG [Error: Failed to extract file error in opening zip file]**

ZIP File:    https://disk.yandex.ru/d/6GSwFkS1Hr2s4g

I can't understand why the archive is not unpacked...

**Comment by plrthink** [comment]
I don't think we can deal with cbr archive, it's not the same as zip.
