### ISSUE TITLE
Does this work with expo?

### ISSUE THREAD

**Issue by jlpg81** [mockingbot/react-native-zip-archive#257]
Hey guys, Im a junior when working with React Native. I was wondering if react-native-zip-archive could work with expo, or if I would have to find something else for expo?
I get the error when using this on expo, and this incompatility seems to be the only reason why I cannot make it work:
error:  [TypeError: null is not an object (evaluating 'RNZipArchive.unzip')]
Thanks!

**Comment by plrthink** [comment]
You should eject the expo app to make it work with this package.
