### ISSUE TITLE
Error install SSZipArchive

### ISSUE THREAD

**Issue by anutting** [mockingbot/react-native-zip-archive#258]
[!] Error installing SSZipArchive
[!] /usr/local/bin/git clone https://github.com/ZipArchive/ZipArchive.git /var/folders/nb/wn3tl6997cq579h_sk371jc0ngkmg_/T/d20220215-40987-14340az --template= --single-branch --depth 1 --branch v2.2.3

Cloning into '/var/folders/nb/wn3tl6997cq579h_sk371jc0ngkmg_/T/d20220215-40987-14340az'...
warning: Could not find remote branch v2.2.3 to clone.
fatal: Remote branch v2.2.3 not found in upstream origin

**Comment by grant-mccarriagher** [comment]
This should be resolved, the dependency restored the older branches.
