### ISSUE TITLE
ld: library not found for -lRNZipArchive - iOS

### ISSUE THREAD

**Issue by vish2595** [mockingbot/react-native-zip-archive#266]
When i am building app in my iPhone then it is showing lRNZipArchive not found.

Xcode Version : 13.4.1 
Iphone Version: 15
React Native Version: 0.64.0
Zip-Archive Version: 6.0.8

**Comment by plrthink** [comment]
It's hard to tell what's going wrong. Does it successfully run on your simulator? Please give the more info.

**Comment by vish2595** [comment]
No, I am running in physical device. When i building the error shown below:

<img width="828" alt="Screenshot 2022-09-06 at 11 21 38 AM" src="https://user-images.githubusercontent.com/21971126/188556899-7d419fc1-e53d-4b3c-9aa0-77cde85d2005.png">

**Comment by vish2595** [comment]
@plrthink Please have a look.

**Comment by plrthink** [comment]
Ok, I would try that on my side at the night(Shanghai timezone).

**Comment by plrthink** [comment]
@vish2595 Sorry for the late response, but I can't reproduce this on my device. Maybe you should double check your installation process?
