### ISSUE TITLE
Old SSZipArchive dependency in iOS podspec

### ISSUE THREAD

**Issue by mgroeneweg** [mockingbot/react-native-zip-archive#271]
Hi,

The podspec fixes the version for SSZipArchive to 2.2.3. Can this restriction be removed or more lenient to newer releases? It prevents using the most recent version of the library. It is used by multiple modules in our app and now I need to stick to an older version.

Thanks in advance.

With regards,

Marcel

**Comment by plrthink** [comment]
Yes, it should be compatible with the SSZipArchive under the semver.

PR are welcome.

**Comment by mgroeneweg** [comment]
Hi,

Just take out the version requirement here:
[https://github.com/mockingbot/react-native-zip-archive/blob/025fed52bc9802a242a19dcfe64a046a0f84ec8b/RNZipArchive.podspec#L17](https://github.com/mockingbot/react-native-zip-archive/blob/025fed52bc9802a242a19dcfe64a046a0f84ec8b/RNZipArchive.podspec#L17)

**Comment by plrthink** [comment]
Just released 6.0.9-beta.0 to address this issue. You can try this one and if everything is ok, we would push this publicly.

**Comment by mgroeneweg** [comment]
Both iOS and Android builds work fine. Thanks!

**Comment by plrthink** [comment]
OK, just published in 6.0.9.
