### ISSUE TITLE
charset GBK or UTF-8 is no work in ios

### ISSUE THREAD

**Issue by donghuiqiu** [mockingbot/react-native-zip-archive#273]
**Describe the bug**
charset GBK or UTF-8 is no work on ios,and the zip files are from windows mechine use GBK to zip

**To Reproduce**
charset GBK or UTF-8 or US-ASCII , I try all and none of them working, android works fine with GBk

<img width="990" alt="图片" src="https://user-images.githubusercontent.com/73329146/202837144-da2ab90c-fbc9-4c9b-8c12-8a730add8aa7.png">

<img width="1569" alt="图片" src="https://user-images.githubusercontent.com/73329146/202837271-a3744883-a169-46d9-93f8-770c973d7234.png">

**Expected behavior**

There's some special chars in xxxx.zip

**Env (please complete the following information):**
 - Device:   IPhone 11 
 - OS: IOS 16.0
 - OS Version: 16
 - Package Version: 6.0.8
 -

**Comment by donghuiqiu** [comment]
I solved

**Comment by plrthink** [comment]
Could you share how you solve the problem?

**Comment by plrthink** [comment]
Actually, we don't use the charset you provided on the iOS platform since it's supposed to be working automatically by the ZipArchvice library, which is used under the hood.

**Comment by donghuiqiu** [comment]
I changed kCFStringEncodingDOSLatinUS to&nbsp;kCFStringEncodingGB_18030_2000 in file SSZipArchive.m, it works for me


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mockingbot/react-native-zip-archive"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月26日(星期六) 晚上6:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mockingbot/react-native-zip-archive] charset GBK or UTF-8 is no work in ios (Issue #273)





 
Actually, we don't use the charset you provided on the iOS platform since it's supposed to be working automatically by the ZipArchvice library, which is used under the hood.
