### ISSUE TITLE
Android unzip process slower than iOS

### ISSUE THREAD

**Issue by utkuimd** [mockingbot/react-native-zip-archive#298]
**Explanation**
Android unzip process slower than iOS, could this speed difference be due to performance of operating systems or is this issue caused by this library?

Is there anything i can do solve this issue?

**Device features**
 - Device: Android emulator Pixel 5
 - OS: Android 10
 - OS API 29
 - Package Version: ^6.0.9

**Comment by plrthink** [comment]
I'm not sure the reason behind this, but I'm how slow it be? like 10x slower?

**Comment by utkuimd** [comment]
I realized that there is no disturbing speed difference between android and ios when i get release apk for android so i close this issue, sorry for disturbing.
