### ISSUE TITLE
Received status code 502 from server: Bad Gateway

### ISSUE THREAD

**Issue by Izocel** [mockingbot/react-native-zip-archive#301]
**Describe the bug**
Seems a package deployment/hosting issue.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve net.lingala.zip4j:zip4j:2.+.
     Required by:
         project :app > project :react-native-zip-archive
      > Failed to list versions for net.lingala.zip4j:zip4j.
         > Unable to load Maven meta-data from https://oss.sonatype.org/content/repositories/snapshots/net/lingala/zip4j/zip4j/maven-metadata.xml.
            > Could not HEAD 'https://oss.sonatype.org/content/repositories/snapshots/net/lingala/zip4j/zip4j/maven-metadata.xml'. Received status code 502 from server: Bad Gateway    
```

```
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 -PreactNativeDebugArchitectures=arm64-v8a -PreactNativeArchitectures=arm64-v8a FAILURE: Build failed with an exception. * What went wrong: Could not determine the dependencies of task ':app:processDebugResources'. > Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'. > Could not resolve net.lingala.zip4j:zip4j:2.+. Required by: project :app > project :react-native-zip-archive > Failed to list versions for net.lingala.zip4j:zip4j. > Unable to load Maven meta-data from https://oss.sonatype.org/content/repositories/snapshots/net/lingala/zip4j/zip4j/maven-metadata.xml. > Could not HEAD 'https://oss.sonatype.org/content/repositories/snapshots/net/lingala/zip4j/zip4j/maven-metadata.xml'. Received status code 502 from server: Bad Gateway * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. BUILD FAILED in 15s.
```

**To Reproduce**
1. Build debugApp

**Expected behavior**
Compile and build run

**Env (please complete the following information):**
 - Android
 - Package Version: 6.1.0
 -  react-native "^0.73.0", --> 0.73.5

**Comment by snailcatcher** [comment]
Same issue:
- Android
- Package Version: 6.1.0
- react-native: 0.73.4

**Comment by Izocel** [comment]
I can confirm that the 'fetch' is ok now :)
Closing the issue

**Comment by samuel-andres** [comment]
I'm having the same error now.

**Comment by vpume** [comment]
I have this problem now, too. I'm completely blocked from building the app, as is everyone else on the team - and we have a deadline tomorrow.

I find it very problematic that we suddenly cannot build our app, because some 3rd party component seems to want to download a document from the internet, which is not available right now. I'm sure this can be done better - why is it necessary to download something on every build? IMHO This should be done on ` npm install` only.

Getting the error:
```
 Failed to list versions for net.lingala.zip4j:zip4j.
         > Unable to load Maven meta-data from https://oss.sonatype.org/content/repositories/snapshots/net/lingala/zip4j/zip4j/maven-metadata.xml.
            > Could not HEAD 'https://oss.sonatype.org/content/repositories/snapshots/net/lingala/zip4j/zip4j/maven-metadata.xml'. Received status code 504 from server: Gateway Time-out
```

**Comment by Balaji-Govind** [comment]
@vpume  did you resolved the issue. It's been more than an half day I'm trying to resolve but I couldn't make it. Please any one help me to resolve.

**Comment by 386sx** [comment]
> @vpume did you resolved the issue. It's been more than an half day I'm trying to resolve but I couldn't make it. Please any one help me to resolve.

as tmizu23 said:
> I'm currently encountering the same error. I managed to fix it and successfully build by making the following changes:
> 
> In `node_modules/react-native-zip-archive/android/build.gradle`, update the dependencies section as follows:
> 
> ```diff
> dependencies {
>     implementation "com.facebook.react:react-native:+"
> -   implementation group: 'net.lingala.zip4j', name: 'zip4j', version: '2.+'
> +   implementation "net.lingala.zip4j:zip4j:2.11.5"
> }
> ```
 works
