### ISSUE TITLE
Broken on XCode 16

### ISSUE THREAD

**Issue by mikkan-39** [mockingbot/react-native-zip-archive#307]
**Describe the bug**
Adter updating to the latest MacOS developer beta, when building a project with XCode 16 for iOS 18.0, following error is thrown:
`/node_modules/react-native-zip-archive/ios/RNZipArchive.m unsupported option '-G' for target 'arm64-apple-ios14.0-simulator'
`

**To Reproduce**
1. Update Xcode to version 16 Beta or install MacOS Sequoia
2. Try to build the project

**Expected behavior**
Builds successfully 

**Env (please complete the following information):**
 - Device: MBP 16 M1 Pro
 - OS: MacOS 
 - OS Version: 15.0 Sequoia Developer Beta 2
 - Package Version: 6.1.1

**Comment by kleberfh** [comment]
@mikkan-39 did you manage to fix this? Any workaround?

**Comment by xiaoosnggao** [comment]
mark

**Comment by bimusiek** [comment]
I found a workaround that can be easily configured in Cocoapods:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'RNZipArchive'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
            file.settings['COMPILER_FLAGS'] = ''
        end
      end
    end
  end
end
```

**Comment by plrthink** [comment]
Maybe I should create a major version for this change.

**Comment by plrthink** [comment]
This should fixed by v7.0.1

**Comment by deepak9705** [comment]
minimum ios version need to increase 15.5

**Comment by Thanaen** [comment]
Do we really have to increase minimum version to 15.5 for a compiler bug? 😕

**Comment by microJ** [comment]
> I found a workaround that can be easily configured in Cocoapods:
> 
> ```ruby
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     if target.name == 'RNZipArchive'
>       target.source_build_phase.files.each do |file|
>         if file.settings && file.settings['COMPILER_FLAGS']
>             file.settings['COMPILER_FLAGS'] = ''
>         end
>       end
>     end
>   end
> end
> ```

Thanks for bimusiek, my variant solution:
1. open `node_modules/react-native-zip-archive/RNZipArchive.podspec`
2. remove the line start with `s.compiler_flags = `, save file change
3. run `npx patch-package react-native-zip-archive` to create patch file. 
4. set up patch-package to project: https://www.npmjs.com/package/patch-package#set-up

**Comment by plrthink** [comment]
> Do we really have to increase minimum version to 15.5 for a compiler bug? 😕

the full story is a little bit longer, but you see from this thread https://github.com/mockingbot/react-native-zip-archive/issues/307#issuecomment-2426475167
