### ISSUE TITLE
react-native-zip-archive TypeError: Cannot read property 'zipFolder' of null

### ISSUE THREAD

**Issue by Arif-Shahriar028** [mockingbot/react-native-zip-archive#308]
I am trying to zip a folder in react-native using react-native-zip-archive. But there is an error: TypeError: Cannot read property 'zipFolder' of null. I have no idea whats going wrong.

This is my code snippet:

```
      const targetPath = `${RNFS.DownloadDirectoryPath}/myFile.zip`
      const sourcePath = RNFS.DownloadDirectoryPath

      console.log("targetpath: ", targetPath)
      console.log("Sourcepath: ", sourcePath)

      try {
        zip(sourcePath, targetPath)
          .then((path) => {
            console.log(`zip completed at ${path}`)
          })
          .catch((error) => {
            console.error(error)
          })
      } catch (error) {
        console.error(`Error in zip: ${error}`);
      }
```

I am getting an error like this:

![image](https://github.com/mockingbot/react-native-zip-archive/assets/61360727/ab7a5d6f-2998-44c8-b153-16e8a0901282)

Can anyone give any idea whats going wrong?

**Comment by plrthink** [comment]
Can you confirm you're linking correctly? Or maybe you're forgetting to run `pod install` in the ios folder of your app? Or you're using expo?

**Comment by Arif-Shahriar028** [comment]
@plrthink thanks for your response!

I opened this issue one month ago, that time I was failed to solve this issue. I was using expo. I couldn't figure out what I did wrong. By the way, then I wrote a basic java module for zip and unzip for android and used this java module by NativeModule of react-native.

**Comment by plrthink** [comment]
> @plrthink thanks for your response!
> 
> 
> 
> I opened this issue one month ago, that time I was failed to solve this issue. I was using expo. I couldn't figure out what I did wrong. By the way, then I wrote a basic java module for zip and unzip for android and used this java module by NativeModule of react-native.

I wish I could reply early.😔
