### ISSUE TITLE
Specs satisfying the `RNZipArchive` dependency were found, but they required a higher minimum deployment target

### ISSUE THREAD

**Issue by vr7bd** [mockingbot/react-native-zip-archive#309]
**Describe the bug**
Trying to run `pnpm expo prebuild` fails with this error:
```
 CocoaPods could not find compatible versions for pod "RNZipArchive":
  In Podfile:
    RNZipArchive (from `../node_modules/react-native-zip-archive`)

Specs satisfying the `RNZipArchive (from `../node_modules/react-native-zip-archive`)` dependency were found, but they required a higher minimum deployment target.
```
**To Reproduce**
Running `prebuild` with expo

**Env (please complete the following information):**
 - Package Version: 7.0.0
 - Expo: 51.020
 - React Native: 0.74.3

**Comment by Praveencena88** [comment]
How did you fix that issue? @vr7bd

**Comment by vr7bd** [comment]
You need to bump up the minimum version on ios to 15.5

**Comment by ra1nj** [comment]
> You need to bump up the minimum version on ios to 15.5

How did you bump up the minimum version ? i changed the **IPHONEOS_DEPLOYMENT_TARGET** to 15.5 in xcode then pod install, still having this issue.

**Comment by ra1nj** [comment]
Solved in https://github.com/mockingbot/react-native-zip-archive/issues/319#issuecomment-2398542588
