### ISSUE TITLE
SSZipArchive pod conflicts with react-native-code-push

### ISSUE THREAD

**Issue by jliukai** [mockingbot/react-native-zip-archive#312]
**Describe the bug**
 `react-native-code-push` and `react-native-zip-archive` both use different versions SSZipArchive.
cannot pod install

cocoapods error:
```
[!] CocoaPods could not find compatible versions for pod "SSZipArchive":
  In Podfile:
    CodePush (from `../node_modules/react-native-code-push`) was resolved to 8.3.1, which depends on
      SSZipArchive (~> 2.2.2)

    RNZipArchive (from `../node_modules/react-native-zip-archive`) was resolved to 7.0.0, which depends on
      SSZipArchive (~> 2.5.5)

    SSZipArchive (= 2.5.5)

Specs satisfying the `SSZipArchive (= 2.5.5), SSZipArchive (~> 2.5.5), SSZipArchive (~> 2.2.2)` dependency were found, but they required a higher minimum deployment target.
```
**To Reproduce**
1. package.json 
```
    "react-native-code-push": "^8.3.1",
    "react-native-zip-archive": "^7.0.0",
```
2. `pod install` and I get the above error.

**Expected behavior**
how to fix different required versions of  SSZipArchive?

**Env (please complete the following information):**
 - Device: iphone 11 simulator
 - OS: mac

similar issue in the past. but these are years old. is there a current solution?
 - https://github.com/mockingbot/react-native-zip-archive/issues/151  <-- shouldve been fixed with v5.
 - https://github.com/mockingbot/react-native-zip-archive/issues/72

**Comment by plrthink** [comment]
You only need to update the minimum deployment target to 15.5, it's required for 7.0.0. version.
