### ISSUE TITLE
Unsupported option "-G" for target "arm64-apple-ios15.6"

### ISSUE THREAD

**Issue by appdevingwoof** [mockingbot/react-native-zip-archive#315]
**Describe the bug**
I recently updated my Mac to macOS 15 Sequoia along with XCode 16. Now whenever I build my app, i get an error "Unsupported option "-G" for target "arm64-apple-ios15.6". 

I have changed the Minimum Deployment version from '13.4' to '15.6' to '17.6'. When I build, I get the error along with the minimum deployment version (ex. if I change it to the minimum deployment to '17.6', the error would be  "Unsupported option "-G" for target "arm64-apple-ios17.6").  

Based on a similar issue found here: https://stackoverflow.com/questions/78608693/boringssl-grpc-unsupported-option-g-for-target-arm64-apple-ios15-0

The compiler flag found under Pods -> RNZipArchive -> Build Phases -> Compile Sources  -> GCC_PREPROCESSOR_DEFINITIONS="HAVE_INTTYPES_H HAVE_PKCRYPT_H HAVE_WZAES HAVE_ZLIB MZ_ZIP_NO_SIGNING $(inherited)" seems to be cause. 

**To Reproduce**
1. Open Project in XCode
2. Select device, and click on Build
3. See error

**Expected behavior**
Build with no errors. 

**Env (please complete the following information):**
- Device: Mac Book Pro 2021
- OS: macOS 15 Sequoia
- Application: XCode 16 

 - Device: iPhone 13
 - OS: 17.7
 
 - Package Version: 7.0.1
 - React-Native": 0.73.9

**Comment by charly-palencia** [comment]
Same issue here 😢

**Comment by JesuHrz** [comment]
Try upgrading to the latest version (7.0.1) @charly-palencia @appdevingwoof

**Comment by 93Kamuran** [comment]
I'm trying it (7.0.1) out for the moment :)

**Comment by appdevingwoof** [comment]
I have the latest version of react-native-zip-archive installed (7.0.1). I followed your steps, (delete package-lock.json, then run pod install). I still have the same error. I am running react-native 0.73.9 - is this possibly an issue? There are no compatibility issues listed.

**Comment by 93Kamuran** [comment]
@appdevingwoof  Try to use ` platform :ios, '15.5'` in your Podfile & use this combination; 

rm -rf node_modules && rm -rf package-lock.json && npm cache clean --force && npm install  && cd ios && rm -rf Pods && pod install --repo-update

**Comment by JesuHrz** [comment]
> I have the latest version of react-native-zip-archive installed (7.0.1). I followed your @JesuHrz steps, (delete package-lock.json, then run pod install). I still have the same error. I am running react-native 0.73.9 - is this possibly an issue? There are no compatibility issues listed.

Trying deleting the `ios/Pods` folder and `ios/Podfile.lock` file

**Comment by appdevingwoof** [comment]
@93Kamuran @JesuHrz Thank you for the taking time out of your day to help. I did the steps you both recommended and I have everything working now. (You both are awesome).
