### ISSUE TITLE
Pod install issue on latest version :  "react-native-zip-archive": "7.0.1",  "react": "18.2.0", "react-native": "0.74.2"

### ISSUE THREAD

**Issue by Pranabemed** [mockingbot/react-native-zip-archive#319]
**Pod Install issue**
issue Note: [!] CocoaPods could not find compatible versions for pod "RNZipArchive/Core":
  In Podfile:
    RNZipArchive/Core (from `../node_modules/react-native-zip-archive`)

Specs satisfying the `RNZipArchive/Core (from `../node_modules/react-native-zip-archive`)` dependency were found, but they required a higher minimum deployment target.

my podfile: 

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'eMedEvents' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
pod 'RNFS', :path => '../node_modules/react-native-fs'
pod 'RNFileViewer', :path => '../node_modules/react-native-file-viewer'
pod 'SSZipArchive'
  pod 'RNZipArchive', :path => '../node_modules/react-native-zip-archive', :subspecs => [
    'Core',
  ]
  target 'eMedEventsTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
Note: 
1.We need solution ,please make it fix

**Comment by ctTushar** [comment]
Same issue

**Comment by plrthink** [comment]
Sorry, but you need to upgrade the iOS deployment as this: https://github.com/plrthink/RNZATestApp/blob/main/ios/Podfile#L4

**Comment by rifad4u** [comment]
Why does changing the IPHONEOS_DEPLOYMENT_TARGET to 15.5 is not working? Setting the same in podfile is working.

**Comment by rifad4u** [comment]
@plrthink  Why does changing the IPHONEOS_DEPLOYMENT_TARGET to 15.5 is not working? Setting the same in podfile is working.

**Comment by plrthink** [comment]
> @plrthink Why does changing the IPHONEOS_DEPLOYMENT_TARGET to 15.5 is not working? Setting the same in podfile is working.

not sure, but i guess there're some extra build steps to make it happen
