### ISSUE TITLE
Build is failing because of 504 error.

### ISSUE THREAD

**Issue by abhishekdexif** [mockingbot/react-native-zip-archive#324]
```
[RUN_GRADLEW]    > Could not resolve net.lingala.zip4j:zip4j:2.+.
[RUN_GRADLEW]      Required by:
[RUN_GRADLEW]          project :app > project :react-native-zip-archive
[RUN_GRADLEW]       > Failed to list versions for net.lingala.zip4j:zip4j.
[RUN_GRADLEW]          > Unable to load Maven meta-data from https://oss.sonatype.org/content/repositories/snapshots/net/lingala/zip4j/zip4j/maven-metadata.xml.
[RUN_GRADLEW]             > Could not HEAD 'https://oss.sonatype.org/content/repositories/snapshots/net/lingala/zip4j/zip4j/maven-metadata.xml'. Received status code 504 from server: Gateway Time-out
```

https://oss.sonatype.org/content/repositories/snapshots/net/lingala/zip4j/zip4j/maven-metadata.xml

is giving 504 error.Build failing.

**Comment by Skaff02** [comment]
I am having the same issue

**Comment by Dr0pG** [comment]
Same issue here

**Comment by ToniIoanas** [comment]
same

**Comment by thepumpkinator** [comment]
same

**Comment by josephattechjays** [comment]
same issue 

Could not HEAD 'https://oss.sonatype.org/content/repositories/snapshots/net/lingala/zip4j/zip4j/maven-metadata.xml'. Received status code 504 from server: Gateway Time-out

**Comment by PiotrSzczepanekVaveHealth** [comment]
As a temporary fix you should change in the build.gradle:

`implementation group: 'net.lingala.zip4j', name: 'zip4j', version: '2.+'` to `implementation("net.lingala.zip4j:zip4j:2.11.4")`

**Comment by 4R0NIN7** [comment]
As a temporary fix you need to change in the build.gradle:
`implementation group: 'net.lingala.zip4j', name: 'zip4j', version: '2.+'` to `implementation("net.lingala.zip4j:zip4j:2.11.4")`

**Comment by anand-bijliride** [comment]
I am also facing this issue, please resolve it

**Comment by Skaff02** [comment]
> As a temporary fix you need to change in the build.gradle: `implementation group: 'net.lingala.zip4j', name: 'zip4j', version: '2.+'` to `implementation("net.lingala.zip4j:zip4j:2.11.4")`

Yes this fixed the issue
for more details you can find this:
implementation group: 'net.lingala.zip4j', name: 'zip4j', version: '2.+'
in android/build.gradle 
in the dependencies section
and replace it with implementation("net.lingala.zip4j:zip4j:2.11.4")

try to run the app after and it will work
