### ISSUE TITLE
NPM release for 0.40 support

### ISSUE THREAD

**Issue by cdlewis** [mockingbot/react-native-zip-archive#33]
Many of us don't feel comfortable pinning a dependency to latest. Would it be possible for you to do an npm patch release?

**Comment by plrthink** [comment]
I'm no familiar with 'npm patch release', but the version 1.0, 0.4.0 support, is already landing on npm.

**Comment by plrthink** [comment]
I'm closing this issue since it's not active, feel free to reopen it on further discussion.
