### ISSUE TITLE
can not use cocoapods ?

### ISSUE THREAD

**Issue by light-of-king** [mockingbot/react-native-zip-archive#35]
Fetching podspec for `RNZipArchive` from `../node_modules/react-native-zip-archive`
[!] The `RNZipArchive` pod failed to validate due to 1 error.
[!] The validator for Swift projects uses Swift 3.0 by default, if you are using a different version of swift you can use a `.swift-version` file to set the version for your Pod. For example to use Swift 2.3, run: 
    `echo "2.3" > .swift-version`:
    - ERROR | attributes: Missing required attribute `homepage`.

**Comment by light-of-king** [comment]
add this in `node_modules/react-native-zip-archive`
```
s.homepage       = "https://github.com/mockingbot/react-native-zip-archive"
```
can work for me

**Comment by plrthink** [comment]
@light-of-king you can fire a pr for this😀

**Comment by plrthink** [comment]
Just checked that also you need to remove the 'v' from the `tag` value.

````diff
- s.source         = { :git => 'https://github.com/mockingbot/react-native-zip-archive.git', :tag => "v#{s.version}"}
+ s.source         = { :git => 'https://github.com/mockingbot/react-native-zip-archive.git', :tag => "#{s.version}"}
````
