### ISSUE TITLE
RCTBridgeModule.h file not found

### ISSUE THREAD

**Issue by uc-asa** [mockingbot/react-native-zip-archive#38]
Hello Team,

I'm using react native version 0.30, but I'm facing RCTBridgeModule.h file not found, please suggest me what should I do.

**Comment by plrthink** [comment]
Sorry for that, you can use the version 0.0.11 of this package for rn<0.40.0.

We're still trying to support all versions of RN. Hope it will ASAP.

**Comment by plrthink** [comment]
I just update it to `1.1.0` which should support all versions of react-native. So I'm going to close this issue, but feel free to re-open it for further questions.
