### ISSUE TITLE
undefined is not an object (evaluating 'RNZipArchive.unzip')

### ISSUE THREAD

**Issue by Juanpe19** [mockingbot/react-native-zip-archive#45]
I'm having an issue when I import the {Unzip} from the library.
The error is the one described in the title.
I've been trying to find another solution than the one already posted here and closed because it wasn't helping, I've tried everything I have in mind and it just won't work in Android. It works fine in iOS.

I'm using:
"react-native": "0.43.3",
"react-native-zip-archive": "^1.1.1"

**Comment by j8seangel** [comment]
Adding this `new RNZipArchivePackage()` in MainAplication.java makes it work for me

**Comment by plrthink** [comment]
@j8seangel it should work fine if you linked it successfully, etc. react-native link.

also, there's a detailed guide on how to manually install it, https://github.com/mockingbot/react-native-zip-archive/issues/43#issuecomment-297610144, maybe we should add this to the readme

**Comment by j8seangel** [comment]
I don't know why the react-native link didn't work well the first time and I had to include it by hand, but I agree on include the manual install in the readme to give it more visibility.

**Comment by slothgeek** [comment]
3 years later i have the same issue with Expo and react-native-zip-archive. @j8seangel  can you explain your solution?
