### ISSUE TITLE
cannot extract .zip file on android

### ISSUE THREAD

**Issue by mikestaub** [mockingbot/react-native-zip-archive#49]
I ran into this exact problem today:
https://stackoverflow.com/questions/15738312/how-to-fix-org-apache-commons-compress-archivers-zip-unsupportedzipfeatureexcept

`java.util.zip.ZipException: only DEFLATED entries can have EXT descriptor`

I saw no obvious way to resolve this using the `java.util.zip` package, so I just used the `org.apache.commons.compress.archivers.zip.ZipArchiveInputStream` class instead as a hack workaround. I documented the neccessary changes in my branch here:
https://github.com/mikestaub/react-native-zip-archive/commit/f8af246aa65387522539aa4a6c26bb5b6bf66216

I am creating this issue in case others run into the same problem, or that you know the proper solution.

**Comment by plrthink** [comment]
@mikestaub cool! maybe you could create a PR to solve this?

**Comment by plrthink** [comment]
Can you try the newest version of the module? Since it has been refactored and not operate the stream directly so I think this issue might not exist anymore.
