### ISSUE TITLE
Can't build after upgrade React Native to 0.45

### ISSUE THREAD

**Issue by truonghoangphuc** [mockingbot/react-native-zip-archive#50]
Hi all,

After I update my project to React Native 0.45, I have trouble with RNZipArchive, I can't build it because it alert "/node_modules/react-native/React/Base/RCTBridgeModule.h:12:9: 'React/RCTDefines.h' file not found" 

Any ideas to fix or I must downgrade React Native ver?

Thanks,

**Comment by plrthink** [comment]
Hi, @truonghoangphuc, I just tested the latest version of this package with rn@0.45.0, it works well on my side. Can you try upgrade react-native-zip-archive to 2.0.0 to see if it works?

**Comment by plrthink** [comment]
I would close this since it's not active for a while, but feel free to reopen it for any related questions.
