### ISSUE TITLE
Package does not use the progress callback while busy

### ISSUE THREAD

**Issue by PeterEmanuel** [mockingbot/react-native-zip-archive#52]
Hi original author,

Are you aware that in the Android version the progress callback is only called once with 0 and once with 1 in unzipStream()? I have not yet checked the iOS code.

I want to have feedback on the name of the entry being unzipped and the extractedBytes so far...
(so I am trying to fix this in a fork).
The name of this entry would be a good extra parameter to the progress callback.

Also, the variable extractedBytes in the unzipStream() function is not used...

Cheers,
Peter

**Comment by plrthink** [comment]
Yeah, actually if you insect the implementations starts [here](https://github.com/mockingbot/react-native-zip-archive/blob/master/android/src/main/java/com/rnziparchive/RNZipArchiveModule.java#L141), then you would see the current solution is just execute the callback only at beginning
and the end. And we could improve this, maybe in next release.

Also you could open PR to this one, we need you help.

**Comment by PeterEmanuel** [comment]
Thanks for getting back. I have already tweaked the Android Java version for the kind of progress info I need. The Objective-C code is more tricky, as it only calls a single function to unzip (not explicitly looping over entries) and I am completely new to Objective-C. I will need some external help for this and I am afraid I cannot offer a PR, because I am only interested in unzipping, not zipping.
Cheers

**Comment by plrthink** [comment]
@PeterEmanuel No, you're welcome to do that, the unzip progress for Android is already helpful for this project and the others would continue to work on this functionality based on your contributions.

Don't feel afraid, this is exactly how open source works :smile:

**Comment by benvium** [comment]
I've tried to implement this a few times in the past - the issue I'm having is that the handy-sounding `ZipEntry#getSize()` and `ZipEntry#getCompressedSize()` methods always return -1 for me, so it's hard to work out the actual progress. You can't compare the number of bytes extracted to the original file file, as (obviously) files are larger when decompressed.

**Comment by benvium** [comment]
I've opened a PR #56 for this.

**Comment by plrthink** [comment]
closing this issue since the PR addressed this issue was merged into the master branch.

feel free to reopen it.
