### ISSUE TITLE
Does it support password?

### ISSUE THREAD

**Issue by genglei01** [mockingbot/react-native-zip-archive#53]
Does it support password? SSZipArchive supports password

**Comment by plrthink** [comment]
By now it not supported yet, but I think it's not very hard to implement, I will add this function ASAP, also you could submit a PR~.

**Comment by GaudamThiyagarajan** [comment]
any update on this. can I unzip a file which was password encrypted from ruby using Zip::Archive.encrypt('filename.zip', 'password')

**Comment by gorvinsky** [comment]
Any update? Does it support unzipping password-protected zip archive now?

**Comment by mohamed-sultan** [comment]
so any one find a solution yet?

**Comment by plrthink** [comment]
I can support this feature in this week

**Comment by jschloer** [comment]
Any progress on this? Is there any way I can help you out?

**Comment by plrthink** [comment]
@jschloer Yeah, sure, it turns out I can't get some time to work this these days, you can feel free to open a PR to deal with this.

**Comment by jschloer** [comment]
Ok, I'll try to carve out some time today for it. Do you have any quick guidance on how you were going to implement it? i.e. parameter names, function names, any gotchas between ios and android I need to worry about?

**Comment by plrthink** [comment]
Thx~

I'm not familiar with Android, but for iOS, it's using SSZipArchive under the hood, and we can utilize it to implement this feature. Perhaps the most relevant code is [here](https://github.com/ZipArchive/ZipArchive/blob/master/SSZipArchive/SSZipArchive.h#L39).

**Comment by jschloer** [comment]
Hmm, ok. I'm not sure if there's a way to support android without bringing in another library like zip4j. Would you be open to an update that large?

**Comment by plrthink** [comment]
I'm ok on this~

**Comment by hitesh96db** [comment]
Hi,

I've raised a PR for Android - https://github.com/mockingbot/react-native-zip-archive/pull/109/

**Comment by premmkumar09** [comment]
Still...?  Is there any solution for adding password while create a zip file?

**Comment by plrthink** [comment]
@premmkumar09 We don't support that right now, however, it should be implemented and I think it's not so difficult to achieve. I would find some time to work on it. Also, it would so be appreciated if anyone contributes to this.

**Comment by plrthink** [comment]
For anyone finds the thread, here're some updates. We do have the ability to unzip the password protected zip file since the release of v4.0.0, but can't archive with the password. And we move to another issue https://github.com/mockingbot/react-native-zip-archive/issues/123 to keep track it.
