### ISSUE TITLE
unable to unzip in ios using native base kitchen sink template

### ISSUE THREAD

**Issue by 32xnabin** [mockingbot/react-native-zip-archive#54]
error log --
[info][tid:com.facebook.react.JavaScript] file:///Users/nepaldigital/Library/Developer/CoreSimulator/Devices/F1729D4C-347F-42EA-9198-8DF061204525/data/Containers/Bundle/Application/BEA0BB92-D9A5-446F-8B2B-1FCC388BB983/NativebaseKitchenSink.app/751.zip
 [info][tid:com.facebook.react.JavaScript] { [Error: unable to unzip]
  line: 2807,
  column: 24,
  sourceURL: 'http://192.168.1.53.xip.io:8081/index.ios.bundle?platform=ios&dev=true&minify=false',
  framesToPop: 1,
  code: 'unzip_error',
  domain: 'RCTErrorDomain',
  userInfo: null,
  nativeStackIOS: 
   [ '0   NativebaseKitchenSink               0x0016125f RCTJSErrorFromCodeMessageAndNSError + 104',
     '1   NativebaseKitchenSink               0x000f6099 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.224 + 96',
     '2   NativebaseKitchenSink               0x0023e8db -[RNZipArchive unzip:destinationPath:resolver:rejecter:] + 310',
     '3   CoreFoundation                      0x24f5c534 <redacted> + 68',
     '4   CoreFoundation                      0x24e8293d <redacted> + 292',
     '5   CoreFoundation                      0x24e863b7 <redacted> + 50',
     '6   NativebaseKitchenSink               0x000f70e7 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 1658',
     '7   NativebaseKitchenSink               0x00146c7b -[RCTBatchedBridge callNativeModule:method:params:] + 734',
     '8   NativebaseKitchenSink               0x00146169 __33-[RCTBatchedBridge handleBuffer:]_block_invoke.477 + 1206',
     '9   libdispatch.dylib                   0x004f2b7f _dispatch_call_block_and_release + 10',
     '10  libdispatch.dylib                   0x004fd493 _dispatch_queue_drain + 2014',
     '11  libdispatch.dylib                   0x004f5de1 _dispatch_queue_invoke + 284',
     '12  libdispatch.dylib                   0x004feecf _dispatch_root_queue_drain + 1790',
     '13  libdispatch.dylib                   0x004fe7cf _dispatch_worker_thread3 + 102',
     '14  libsystem_pthread.dylib             0x24c89b29 _pthread_wqthread + 1024',
     '15  libsystem_pthread.dylib             0x24c89718 start_wqthread + 8' ] }

**Comment by plrthink** [comment]
you mean this one?

https://github.com/GeekyAnts/NativeBase-KitchenSink

**Comment by 32xnabin** [comment]
that's right I have cloned this repo and tried to unzip after downloading a zip file

**Comment by plrthink** [comment]
ok, I will check that ASAP

**Comment by plrthink** [comment]
finally got some time to take a look. really sorry for the delay.

Do you still have this issue? I can successfully use react-native-zip-archive with nativebase-kitchensink project, and here is the app https://github.com/plrthink/NativeBase-KitchenSink.

I'm going to close this since it seems not a problem with the package itself. But feel free to comment more if you still have problems with this.
