### ISSUE TITLE
unzip in background thread

### ISSUE THREAD

**Issue by plrthink** [mockingbot/react-native-zip-archive#57]
Since this great PR https://github.com/mockingbot/react-native-zip-archive/pull/56 was merged into the master, it's reasonable to make iOS side works in the same way:

- unzip in the background thread
- give the real progress event, not just emitted at the beginning and the end.

PRs are welcome.

**Comment by plrthink** [comment]
cc @AmatsuZero @benvium @PeterEmanuel

**Comment by benvium** [comment]
Good idea @plrthink.

For reference, this document describes how to manage background threads in iOS RN Modules:
https://facebook.github.io/react-native/docs/native-modules-ios.html

**Comment by plrthink** [comment]
@benvium thanks, will check it out

**Comment by plrthink** [comment]
just inspected the code more carefully, we have already implemented the accurate progress since we use implemented the delegate method `zipArchiveProgressEvent` which should works as expected.

@peteremanuel could you try that again? maybe the zip file is too small to emit events.

**Comment by plrthink** [comment]
Just shipped a new release to npm with a lot of fixes and new features like unzipping on a separate thread. So I'm going to close this.
