### ISSUE TITLE
your RNZipArchive.podspec is error 

### ISSUE THREAD

**Issue by zhumoyong** [mockingbot/react-native-zip-archive#61]
s.subspec 'RNZASSZipArchive' do |ss|
    ss.source_files = 'ios/# `RNZASSZipArchive`/*.{h,m}', 'ios/RNZASSZipArchive/aes/*.{h,c}', 'ios/RNZASSZipArchive/minizip/*.{h,c}'
    ss.private_header_files = 'ios/RNZASSZipArchive/*.h', 'ios/RNZASSZipArchive/aes/*.h', 'ios/RNZASSZipArchive/minizip/*.h'
  end

**Comment by zhumoyong** [comment]
you can use previous version about RNZipArchive.podspec

**Comment by plrthink** [comment]
Yeah, also the fixed version has been merged into the master branch, so it will be shipped in next release.

**Comment by zhumoyong** [comment]
you can push to npmjs, npmjs id old version
