### ISSUE TITLE
[Android] Couldn't zip on RN 0.46.4

### ISSUE THREAD

**Issue by mesbahsabur** [mockingbot/react-native-zip-archive#64]
I get this error when trying to zip a folder on Android 7.0 (Galaxy 8) (Update: same on simulator Android 6.0)

```
Error: Couldn't zip /data/user/0/com.myapp/files/backup.zip
    at createErrorFromErrorData (NativeModules.js:121)
    at NativeModules.js:78
    at MessageQueue.__invokeCallback (MessageQueue.js:301)
    at MessageQueue.js:118
    at MessageQueue.__guard (MessageQueue.js:228)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:117)
    at debuggerWorker.js:71
```

Unzip works fine though...!

I'm running latest master commit.
All worked fine on RN 0.43.3, but this happens on RN 0.46.4

iOS zip and unzip work fine too btw!

**Comment by mesbahsabur** [comment]
I think it may have something to do with the fact that I'm trying to zip a folder that contains an empty folder... 

`08-05 23:24:41.203 18129-21085/com.cirqr W/System.err: java.io.FileNotFoundException: /data/user/0/com.cirqr/files/productData/3hrn4GMHzoZ3BGby (Is a directory)`

**Comment by mesbahsabur** [comment]
I managed to fix this temporarily by using this guy's zip functions instead: https://stackoverflow.com/a/41653409/7937660

**Comment by plrthink** [comment]
@mesbahsabur Cool, would you like to open a PR to fix this? That would be helpful.

**Comment by plrthink** [comment]
can anyone experienced this issue try the code on the master branch? if the library has fixed this issue, thanks the PR brought by @Deividy , I would release the patch ASAP.

**Comment by ferminmoli** [comment]
I'm using react-native 0.54.0 and it is not working also. Is there any workaround for this?
