### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by aschenkel** [mockingbot/react-native-zip-archive#66]
Update npm package to match master and be compatible with RN 0.47

As a workaround I'm using     

`"react-native-zip-archive": "github:mockingbot/react-native-zip-archive#c0bc574e6244a9a9bbd489c4a42170674af389ad"`

**Comment by plrthink** [comment]
Sorry for late response. I'm still working on this issue occasionally, and I would ship a version when it's solved, maybe this weekend.

So, I will come back when I can finish it and keeps this issue open during this period.

**Comment by plrthink** [comment]
Just shipped a new release to npm with a lot of fixes and new features like unzipping on a separate thread. So I'm going to close this.
