### ISSUE TITLE
[iOS]: 2.1.0 doesn't work with CodePush when installed with CocoaPods

### ISSUE THREAD

**Issue by itchingpixels** [mockingbot/react-native-zip-archive#72]
Hey! We're trying to also use react-native-zip-archive with code push and bumping into another issue:

It seems like now that both react-native-zip-archive and codepush includes ssziparchive, some of the code won't compile because of duplicate struct definitions.

![image](https://user-images.githubusercontent.com/5416288/31835819-f43df960-b5ca-11e7-9b18-70aeafa3e67d.png)

**Comment by itchingpixels** [comment]
We can fix this short-term by forking react-native-zip-archive, but what would be the plan to fix this long-term?

**Comment by chirag04** [comment]
forking and removing all the ssarchive stuff and providing a header path in code push is what i do right now. https://github.com/chirag04/react-native-zip-archive/tree/ssziparchive2

**Comment by itchingpixels** [comment]
@chirag04 : I think you're using a quite outdated version of react-native-zip-archive there, since SSArchive has been renamed since then in the repo, so we can not use one SSArchive as the dependency for both codepush & react-native-zip-archive as currently stands.

I believe we depending on a newer version that has lots of vital fixes.

**Comment by itchingpixels** [comment]
Thanks for the suggestion though:)

Probably we'll also end up doing something similar, but with a newer version of this lib.

@plrthink : do you have any suggestions?

Shouldn't the conflicting struct be also renamed, if the rename was a conscious choice?

**Comment by plrthink** [comment]
@itchingpixels Yeah, I have renamed the ssziparchive just to solve the duplicate symbol issue when using with codepush. But our use case is in a pure react-native way, which means installed with npm. So we didn't run into this situation.

I'm still not sure the correct way to solve this problem. Renaming is kind of a workaround, but not maintainable. I would take a look at it, and any advice or PR is welcome.

**Comment by itchingpixels** [comment]
I've looked into it and got it working by:
- Using SSZipArchive pod, not the one that has been bundled with either react-native-zip-archive nor with CodePush (so both of the subspecs are left out, and only using "Core")
Looks like this:
```
  pod 'CodePush', :path => '../node_modules/react-native-code-push', :subspecs => [
    'Core', 'JWT', 'Base64'
  ]
  pod 'SSZipArchive'
  pod 'RNZipArchive', :path => '../node_modules/react-native-zip-archive', :subspecs => [
    'Core',
  ]
```
- Modify the imports to `#import <SSZipArchive/SSZipArchive.h>` in RNZipArchive.h, and remove the RNZA prefix from class names.
- No change in CodePush is required as far as I can tell.

This setup both compiles CodePush & react-native-zip-archive successfully with Cocoapods.

The problem could mismatching versions of SSZipArchive being used - what's the version react-native-zip-archive exactly depends on?

I'll also try whether this actually works run-time as well, and report back.

**Comment by itchingpixels** [comment]
Obviously this will not solve the non-cocoapods problem, where these two libraries will clash.
We'll probably start using our own fork of react-native-zip-archive, that we can make work with CodePush & cocoapods.

But I'm not sure how the original problem could be solved then - conflicting class names when _not_ using Cocoapods. How do other libraries deal with this issue?

I don't really have a suggestion there - renaming the structs could be fine, I guess (?)

**Comment by plrthink** [comment]
As far as I can tell, the current solution works well with npm. I'm not sure what's the difference between it and cocopod installed. Maybe the .xcworkspace? I did some search before but with no luck at all. So I have to rename the class as a workaround.

And I believe the version of SSZipArchive is 1.6.1 which updated in this PR, which reminds me I should update it to the latest version.🤔

I wish react-native would have a strategy to solve this problem, I mean l would just use like cocopod by declaring the version of the native dependency in the package.json and it would download and link for me.  After all, there're so many react-native packages works as a wrapper of existing native packages as this one on the iOS side.

**Comment by itchingpixels** [comment]
Yeah, I guess if rnpm was a real dependency manager, this could be solved:).

I believe react-native will put more emphasis on Cocoapods in the future (at least they're talking about better rnpm compatibility), but let's see!

We've forked react-native-zip-archive, this is the diff:
https://github.com/languagedrops/react-native-zip-archive/commit/06e07629a395738fedc15881f144eea513d5447f

and the Podfile needs to look like this:

```
 pod 'CodePush', :path => '../node_modules/react-native-code-push', :subspecs => [
    'Core', 'JWT', 'Base64'
  ]
  pod 'SSZipArchive'
  pod 'RNZipArchive', :path => '../node_modules/react-native-zip-archive', :subspecs => [
    'Core',
  ]
```

I personally think that people should use to manage their iOS react-native dependencies via Cocoapods, the above mentioned reason (rnpm is not a dependency manager - and bundling shared dependencies multiple times is not advisable in general), but that's just me:)

**Comment by plrthink** [comment]
Thanks for sharing~

For me, I would prefer npm since I came from a JavaScript developer not familiar with Cocopod before. But that really depends.

I would still try to fix this, hope I will find a nice way.

**Comment by StanislavMayorov** [comment]
> We've forked react-native-zip-archive, this is the url:
> https://github.com/languagedrops/react-native-zip-archive/

In our case project compiles okay when we add code-push. But `unzip` work differently. `unzip` creates file instead folder. 
We have used code-push v5.5 and react-native-zip-archive v3.1. languagedrops's fork fix the issue.

**Comment by pedrosimao** [comment]
@itchingpixels I have tried the Cocoapods solution, but I get this error on `pode install`: `CocoaPods could not find compatible versions for pod "CodePush/Base64"`

**Comment by plrthink** [comment]
Hi, folks,  I just release the alpha version, 5.0.0-alpha.0, which utilize the react-native@^0.60.0 to resolve SSZipArchive via cocoapods. That is to say, we can finally fix this problem in a standard way.🥰

Please test it on your use cases to see if it works. Also to remind, these changes requires react-native's version is at least 0.60.0.
