### ISSUE TITLE
zip/unzip variable value

### ISSUE THREAD

**Issue by pstanton** [mockingbot/react-native-zip-archive#75]
is it currently possible to zip or unzip a variable value ie not a file/asset?

something like:

let text = 'some ascii text that can be zipped';
let bytearray = zip(text);

**Comment by plrthink** [comment]
I think it could not be done currently, but I' curious about what you expected the result? A zip file contains a text file or something else? maybe we could implement it.

**Comment by pstanton** [comment]
here's something i wrote for java 

I'd be surprised if the equiv was not possible in iOS, maybe something [like this](https://github.com/nicklockwood/GZIP/tree/master/GZIP) ?

	```
	public static byte[] compress(byte[] input) throws IOException {
		Deflater d = new Deflater(Deflater.BEST_COMPRESSION, false);
		d.setInput(input);
		d.finish();

		try (ByteArrayOutputStream bos = new ByteArrayOutputStream(input.length)) {
			byte[] buf = new byte[1024];
			while (!d.finished())
				bos.write(buf, 0, d.deflate(buf));
			d.end();
			return bos.toByteArray();
		}
	}

	public static byte[] decompress(byte[] input) throws IOException, DataFormatException {
		Inflater i = new Inflater();
		i.setInput(input);

		try (ByteArrayOutputStream bos = new ByteArrayOutputStream(input.length)) {
			byte[] buf = new byte[1024];
			while (!i.finished())
				bos.write(buf, 0, i.inflate(buf));
			i.end();
			return bos.toByteArray();
		}
	}
```

**Comment by plrthink** [comment]
Thanks for your contributions, but I think the main concern of this package is zip and unzip the files. So I'm sorry to say this may not be implemented in this module.

**Comment by pstanton** [comment]
ok. anyone else need what i need, look at [gzip-js](https://www.npmjs.com/package/gzip-js) 

it does what i need, however a native impl would have been more efficient i would have thought.
