### ISSUE TITLE
Unable to unzip files in react-native-zip-archive in background

### ISSUE THREAD

**Issue by RamkumarBPE** [mockingbot/react-native-zip-archive#76]
Hi,
I would like to like Unzip the zip file in background, Can anyone tell me How to do this?

If Un-zipping, it is getting cancelled in the mid, if I go to some other screen

Kindly help me on this.

**Comment by plrthink** [comment]
I'm afraid that it can't be achieved on iOS right now, see this issue (https://github.com/facebook/react-native/issues/167) for more info. But on Android, we have the headless js API which allows us to address this. We could implement this.

**Comment by hariDasu** [comment]
is there a way to force the app to prevent the phone from entering the background? like if on a loading screen can we force the app to remain open and active?
