### ISSUE TITLE
iOS: Unable to unzip after upgrading React Native to 0.52.0

### ISSUE THREAD

**Issue by Bramvanosta** [mockingbot/react-native-zip-archive#81]
Hello,

I tried using this package on a new RN project using version 0.52.0 and I couldn't get it to unzip, it gave me the error "unable to unzip".

I tried running the example given in this repository, and everything worked fine. I then upgraded the version of RN used from 0.48.4 to 0.52.0 (and React from 16.0.0-alpha.12 to 16.2.0) and the error came back.

```
Error: unable to unzip
    at createErrorFromErrorData (1502c86f-3c8c-4ead-a…0-11a52f74cecf:7068)
    at 1502c86f-3c8c-4ead-a…0-11a52f74cecf:7020
    at MessageQueue.__invokeCallback (1502c86f-3c8c-4ead-a…0-11a52f74cecf:7462)
    at 1502c86f-3c8c-4ead-a…0-11a52f74cecf:7207
    at MessageQueue.__guardSafe (1502c86f-3c8c-4ead-a…0-11a52f74cecf:7375)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (1502c86f-3c8c-4ead-a…0-11a52f74cecf:7206)
    at debuggerWorker.js:72
```

**Comment by Bramvanosta** [comment]
The test zip file I was using seemed to be wrong or something.

**Comment by aokoruyucu** [comment]
I get same error on ios simulator too. any help?

`"react-native": "0.55.4",
    "react-native-fs": "^2.10.14",
    "react-native-zip-archive": "^2.2.6",`

**Comment by plrthink** [comment]
@aokoruyucu could you provide your zip file so I can test it to see what's going wrong.

**Comment by aokoruyucu** [comment]
@plrthink sorry for the late reply. here is my zip file.
[test.zip](https://github.com/mockingbot/react-native-zip-archive/files/2160369/test.zip)
