### ISSUE TITLE
Chinese file name garbled

### ISSUE THREAD

**Issue by Thyiad** [mockingbot/react-native-zip-archive#82]
When the file name is not english, it will garbled.
How to fix it ...

**Comment by plrthink** [comment]
I think the OSs(iOS and Android) has already taken care of this. Can you try this repo https://github.com/plrthink/react-native-zip-archive-none-ASCII-path-name to see this behavior? It works as expected on my side.

**Comment by plrthink** [comment]
closed due to has already solved in the latest version ( 2.2.2)
