### ISSUE TITLE
cannot use async/await

### ISSUE THREAD

**Issue by kanalasumant** [mockingbot/react-native-zip-archive#83]
Hello. Thank you for this wonderful library. I encountered an issue where I've used the unzipping and zipping commands using async/await and they don't work as expected, since I thought the results are promises. The documentation mentioned promises way **works** just fine. Is this a bug or am I doing something wrong, I'm not sure. Let me know if you tried this, I'd appreciate it.

**Comment by plrthink** [comment]
Could you show some snippets you're using? I can successfully use the API with async/await. So maybe there's something wrong with your code.

**Comment by skyforeverGE** [comment]
@kanalasumant @plrthink : probably, I know what is going on because i got the same situation; remove the try catch block then try again

**Comment by plrthink** [comment]
@skyforeverGE Sorry I don't get it, you mean which try catch block?
