### ISSUE TITLE
我建议可以把配置信息写全一点，对于很多JavaScript过来的可能配置比较困难

### ISSUE THREAD

**Issue by tanjun210** [mockingbot/react-native-zip-archive#86]
在MainApplication.java文件下加入

import com.rnziparchive.RNZipArchivePackage;  //here

@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new RNZipArchivePackage()   //here
      );
    }

**Comment by plrthink** [comment]
可以在根目录下跑 `react-native link`，cli 会自动完成这些
