### ISSUE TITLE
[Android] Couldn't zip on RN 0.54.0

### ISSUE THREAD

**Issue by ferminmoli** [mockingbot/react-native-zip-archive#90]
Error: Couldn't zip /data/user/0/com.mobileapp/files/syncFiles/93604/photos1.zip
at createErrorFromErrorData (C:\Projects\mobile\Mobile\node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:123)
at C:\Projects\mobile\Mobile\node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:80
at MessageQueue.__invokeCallback (C:\Projects\mobile\Mobile\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:400)
at C:\Projects\mobile\Mobile\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:139
at MessageQueue.__guardSafe (C:\Projects\mobile\Mobile\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:316)
at MessageQueue.invokeCallbackAndReturnFlushedQueue (C:\Projects\mobile\Mobile\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:138)
at debuggerWorker.js:72

I'm using react-native 0.54.0 and it is not working also. Is there any workaround for this?

**Comment by plrthink** [comment]
Just tried it with react-native@0.54.0 but can't reproduce the issue, could you please provide a working example? also a more detailed info about your environment like which sdk version you're targeting?

**Comment by ferminmoli** [comment]
SDK: 23

Theese are the libraries that I'm using:


    "appcenter": "^1.0.0",
    "appcenter-analytics": "^1.0.0",
    "appcenter-crashes": "^1.0.0",
    "appcenter-push": "^1.0.0",
    "axios": "^0.16.2",
    "create-react-class": "^15.6.2",
    "crypto-js": "^3.1.9-1",
    "lodash": "^4.17.4",
    "moment": "^2.19.2",
    "native-base": "2.3.5",
    "prop-types": "^15.6.0",
    "react": "^16.3.0-alpha.1",
    "react-native": "0.54.0",
    "react-native-code-push": "^5.2.1",
    "react-native-crop-image": "github:Radweb/react-native-crop-image",
    "react-native-datepicker": "^1.6.0",
    "react-native-device-info": "^0.13.0",
    "react-native-extended-stylesheet": "^0.8.0",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-fs": "^2.8.5",
    "react-native-get-real-path": "git+https://github.com/Wraptime/react-native-get-real-path.git",
    "react-native-image-crop-picker": "^0.18.1",
    "react-native-image-gallery": "^2.1.3",
    "react-native-image-rotate": "^2.0.0",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-local-mongodb": "1.8.2",
    "react-native-mail-compose": "^0.0.5",
    "react-native-orientation": "^3.1.0",
    "react-native-pdf": "1.3.0",
    "react-native-permissions": "1.0.1",
    "react-native-router-flux": "^4.0.0-beta.27",
    "react-native-signature-capture": "^0.4.9",
    "react-native-tab-view": "0.0.67",
    "react-native-vector-icons": "^4.3.0",
    "react-native-zip-archive": "^2.1.0",
    "react-redux": "^5.0.6",
    "react-tween-state": "^0.1.5",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0"

**Comment by ferminmoli** [comment]
I can't give an example because our app is very complex. There's something else that I can do?

**Comment by plrthink** [comment]
@ferminmoli maybe the folder you want to zip would be helpful

**Comment by ferminmoli** [comment]
I'm still getting the same error. My folder is:

Error: Couldn't zip 

/data/user/0/com.mobile/files/syncFiles/93003/photos1.zip

**Comment by ferminmoli** [comment]
It works on 2.2.2. Thanks!
