### ISSUE TITLE
Link manually package

### ISSUE THREAD

**Issue by baxri** [mockingbot/react-native-zip-archive#92]
# LINK MANUALLY

Can Anyone help me how to link this package manually, also it will be good to add this in README documentation. 

Every package has its manually linking guide.

**Comment by plrthink** [comment]
Does `react-native link` work for you? And [react-native's official](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#docsNav) guide already includes that but only for iOS.

**Comment by baxri** [comment]
Yeah, the react-native link has some problems on my project I need manually linking, in docs, there are only for IOS yes.  Are you going to add this manually linking guide in README?

**Comment by plrthink** [comment]
sure, has updated that in the readme. hope would help you integrate the package.

**Comment by baxri** [comment]
It works, thank you so much :)
