### ISSUE TITLE
Cannot open zipped file on desktop

### ISSUE THREAD

**Issue by annelorraineuy** [mockingbot/react-native-zip-archive#97]
When trying to zip 4 .csv files on the NAT app using this package, I cannot open the resulting zipped file. 

_Please see the ff errors:_

**On WINDOWS**
```
7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_CA.UTF-8,Utf16=on,HugeFiles=on,4 CPUs)

Error: /home/user/Desktop/myZipFile.zip: Can not open file as archive

Errors: 1
```

**On OS X**
`Unable to expand "myZip.zip" into "Desktop". (Error 1 - Operation not permitted.)`

**react-native: 0.44.2
react-native-zip-archive: ^2.2.6**

--- 
Any leads or insights?

**Comment by plrthink** [comment]
sorry, I dont get what is the NAT app? could you give a reference?

**Comment by annelorraineuy** [comment]
@plrthink apologies, i just meant our react native app. 
Context: from the app i create csv files and save them into one folder, and i tried to use this package to zip the contents of said folder into one .zip file. The resulting zip file cannot be opened producing those errors. Any ideas?

**Comment by plrthink** [comment]
not sure what's going wrong here. could you give a zip file to reproduce this issue? that would be helpful.

**Comment by annelorraineuy** [comment]
Outputted zipped file: [example_zip_with_Error_1.zip](https://github.com/mockingbot/react-native-zip-archive/files/2185176/example_zip_with_Error_1.zip)

Here is the code I did:
```
import { zip } from 'react-native-zip-archive'

const dirs = RNFetchBlob.fs.dirs
const OS_PATH = Platform.OS === 'ios' ? dirs.DocumentDir : dirs.DownloadDir
const TARGET_EXPORT_PATH = `${OS_PATH}/export`
const TIME_STAMP = moment().format('MM-DD-YYYY--kk-mm').toString()
const ZIP_FILENAME = `${TARGET_EXPORT_PATH}/myExportedZip-${TIME_STAMP}.zip`
 
zip(TARGET_EXPORT_PATH, ZIP_FILENAME)
.then((path) => {
  console.log(`zip completed at ${path}`)
})
.catch((error) => {
  alert('Error: ' + error)
})
```

**Comment by annelorraineuy** [comment]
@plrthink additional info to above: I tested this on iOS Simulator

**Comment by annelorraineuy** [comment]
@plrthink I installed `react-native-zip-archive@2.2.0` and it works with this version!

**Comment by plrthink** [comment]
@annelorraineuy it still an issue to me, would fix it ASAP

**Comment by annelorraineuy** [comment]
@plrthink i already mentioned the directory structure. Its up there in recent messages. 


const OS_PATH = Platform.OS === 'ios' ? dirs.DocumentDir : dirs.DownloadDir
const TARGET_EXPORT_PATH = `${OS_PATH}/export`
