### ISSUE TITLE
Can't zip .mp3 file

### ISSUE THREAD

**Issue by gabyckaz** [mockingbot/react-native-zip-archive#99]
I'm trying the example code to zip files, it works great with an .txt file but now I'm using a .mp3 file and I keep getting the following error
![image](https://user-images.githubusercontent.com/11955577/44174268-db0b5f80-a09f-11e8-9844-e6e389af0d18.png)
The code is exactly the same, the only diference is the name and the file extention

**Comment by plrthink** [comment]
Could you confirm the mp3 file is in the fs already? I can't reproduce it with the same setup.

**Comment by gabyckaz** [comment]
I'm sorry but I'm not longer working on this project
